### ISSUE TITLE
Installer won't install

### ISSUE THREAD

**Issue by WaterRatj** [luvit/luvit#1003]
Can't get the installer to work.
Keep getting the error.

"/home/tim/luvi/src/lua/luvibundle.lua:277: ERROR: /tmp/lit.zip is not a zip file or a folder"

When manual compile can't install any package or i get an error.

**Comment by IcedCoffeee** [comment]
same, looks like https://lit.luvit.io/ is down

**Comment by creationix** [comment]
Yep, it was down.  I noticed and rebooted the server.  It appears to be still up for now.

**Comment by jknotts** [comment]
Could you reboot the server again. I ran into the same issue tonight. Thanks.

**Comment by rphillips** [comment]
hmm. restarted... my cron didn't trigger... i'll check on it

**Comment by SinisterRectus** [comment]
By the way, searching https://luvit.io/lit.html only sometimes works. I wonder if this is related to or causing the issue.
