### ISSUE TITLE
Website is offline

### ISSUE THREAD

**Issue by monofur** [luvit/luvit#1004]
I am wondering when the website will be online again? I need to make a new install of luvit and forgot how to do it on linux, and the provided tutorial on building from source is failing, saying it can't find a zip file named "lit.zip" (or something about saying it isn't a zip file or a folder).

Is this project dead?

**Comment by squeek502** [comment]
Not dead, but the lit server seems to be going down a lot. @creationix or @rphillips should be able to restart it soon.

Note that you can build from source, but to do so you'd need to get [luvi](https://github.com/luvit/luvi), then build [lit](https://github.com/luvit/lit), and then build luvit.

**Comment by rphillips** [comment]
restarted
