### ISSUE TITLE
Getting ECONNRESET when make https request

### ISSUE THREAD

**Issue by Playermet** [luvit/luvit#1005]
Problem URL: https://app.asana.com/api/1.0/workspaces
OS: Windows 7 x64
Luvit: 2.14.2

```lua
local https = require 'https'

local req = https.get('https://app.asana.com/api/1.0/workspaces', function (res) end)
req:on('error', p)
req:done()
```

Curl and firefox make request properly.
Code above get ECONNRESET error.
Asana without ssl works, but just returns redirect to ssl version.
Other sites with ssl (https://luvit.io for example) works fine.

Tried:
 - use other pc
 - set exact same headers as curl, firefox

Nothing helped.

**Comment by SinisterRectus** [comment]
Looks like another  SSL/TLS issue.

**Comment by SinisterRectus** [comment]
Cannot reproduce. Is this still an issue?

**Comment by Playermet** [comment]
Probably not. Issue can be closed.
