### ISSUE TITLE
Out of date openssl

### ISSUE THREAD

**Issue by DannehSC** [luvit/luvit#1009]
The [luvit-openssl](https://github.com/luvit/lua-openssl) fork is very, very out of date. I would like to see it updated. The current `openssl.hmac.version` value is `hmac library for Lua 5.1 / Nov 2014 / based on OpenSSL 1.0.0`

**Comment by DannehSC** [comment]
Doesn't explain why hmac.version says nov 2014. 🤔

**Comment by squeek502** [comment]
That bit is [hard coded](https://github.com/zhaozg/lua-openssl/blob/50bc5fb28604ee3ca6a750c6a3519167bb5b4861/src/hmac.c#L12). I'm not familiar enough with lua-openssl to know what it refers to.

**Comment by rphillips** [comment]
@DannehSC it appears to be hardcoded in the lua-openssl [source](https://github.com/zhaozg/lua-openssl/blob/master/src/hmac.c#L12).

**Comment by DannehSC** [comment]
Well, back to the drawing board on why this won't work.

**Comment by rphillips** [comment]
@DannehSC what are you trying to get working?

**Comment by DannehSC** [comment]
The lua rethinkdb driver doesn't work with luvit, so I decided "Well. Multiple people need this. I'll finally make something that can benefit people." and started. Then authentication decided to give me heck. In short, authentication for rethink wrongly claims "wrong password".
