### ISSUE TITLE
Get CPU and RAM usage

### ISSUE THREAD

**Issue by Ale32bit** [luvit/luvit#1013]
Is there a way to get the CPU and RAM usage?

**Comment by squeek502** [comment]
You can using the [`luv` bindings](https://github.com/luvit/luv/blob/96591671bc468b842b11301e9b374b13b7b5c768/src/luv.c#L225-L262).

```
local uv = require('uv')

local cpuinfo = uv.cpu_info()
p(cpuinfo)

local totalMem = uv.get_total_memory()
local freeMem = uv.get_free_memory()
local usedMem = totalMem - freeMem
print(string.format("%d used (out of %d)", usedMem, totalMem))
```

`uv.cpu_info()` will output [the same thing as node's `os.cpus()`](https://nodejs.org/api/os.html#os_os_cpus), and can be [used in similar ways to get % usage, etc](https://stackoverflow.com/questions/36816181/get-view-memory-cpu-usage-via-nodejs) (wouldn't be too hard to [port this to luvit](https://github.com/oscmejia/os-utils/blob/master/lib/osutils.js#L165-L213)).

`uv.get_total_memory` and `uv.get_free_memory` return the number of bytes total/free (the same as node's `os.totalmem`/`os.freemem`).
