### ISSUE TITLE
Lit Package search not working

### ISSUE THREAD

**Issue by renatosc** [luvit/luvit#1015]
https://luvit.io/lit.html

It appears to be CORS issue...

Failed to load https://lit.luvit.io/search/*: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://luvit.io' is therefore not allowed access. The response had HTTP status code 504.

**Comment by renatosc** [comment]
I didn't pay attention to the http error code. Good catch. 

It happens with any search (not only search "*"), so I wouldn't think that is just a timeout issue due to large processing amount. Maybe is it an issue in the query itself?

**Comment by creationix** [comment]
Some queries work, but it's pretty bad.  Most will fail.

**Comment by renatosc** [comment]
Got it. Let me know if I can be of any assistance. I would gladly take a look on the query code for you.

**Comment by creationix** [comment]
You're welcome to.  It's pretty simple and naive.  There are basically no indexes and extracting the data can be slow.  Some in-memory indexes at a minimum would help a lot.

**Comment by creationix** [comment]
https://github.com/luvit/lit/blob/master/libs/pkg.lua#L86-L168

**Comment by squeek502** [comment]
Fixed by https://github.com/luvit/lit/pull/267
