### ISSUE TITLE
Question about require's module cache?

### ISSUE THREAD

**Issue by RensAlthuis** [luvit/luvit#1025]
I'm hosting a discord bot using Discordia which is an API based on luvit, and I was trying implement a feature that allows me to write code without having to reboot the bot every time I change something (going for that 100% uptime :3 ). 
I figured I could just use "require" to reload a module and the bot would use the changed version. Sadly.. It didn't, i'm pretty sure that's because require uses a cache to store any previously loaded modules.

In light of that I was wondering if there is some way of invalidating the module cache so require is forced to reload the module from file as opposed to the cache?

**Comment by SinisterRectus** [comment]
To avoid side-effects, Luvit's does not expose its require cache. You'll have to write your own loader. If you want some inspiration, you can look at what I use [here](https://github.com/SinisterRectus/Luna/blob/master/loader.lua).

**Comment by RensAlthuis** [comment]
Oh thanks a lot, I'll give a try!
