### ISSUE TITLE
download string error

### ISSUE THREAD

**Issue by Hmm465GamingYT** [luvit/luvit#1026]
when i do PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"

it comes to an error:
Exception calling "DownloadString" with "1" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1 iex ((new-object net.webclient).DownloadString('https://github.com/lu ...
 CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
FullyQualifiedErrorId : WebException

**Comment by SinisterRectus** [comment]
I have no idea why this is happening. To compensate, I wrote a luvi app that implements the PS script in Lua: https://github.com/SinisterRectus/get-lit

See also luvit/luvi#234

**Comment by squeek502** [comment]
Looks like this is the issue: https://stackoverflow.com/questions/41618766/powershell-invoke-webrequest-fails-with-ssl-tls-secure-channel

> By default powershell uses TLS 1.0 the site security requires TLS 1.2

This works for me:
```
PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "[Net.ServicePointManager]::SecurityProtocol =  'Tls12'; iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"
```
