### ISSUE TITLE
REPL autocomplete crash on assignment

### ISSUE THREAD

**Issue by aiverson** [luvit/luvit#1035]
Attempting to autocomplete code on the right side of an assignment crashes the REPL.

`sqrt = math.sq` crashes the REPL on attempts to autocomplete with the error message
```Uncaught Error: [string "bundle:deps/repl.lua"]:183: [string "bundle:deps/repl.lua"]:138: bad argument #1 to 'setfenv' (number expected, got nil)
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/repl.lua"]:183: in function <[string "bundle:deps/repl.lua"]:182>
        [C]: in function 'run'
        [string "bundle:init.lua"]:52: in function <[string "bundle:init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
```

The autocomplete generates and attempts to compile syntactically incorrect code, but doesn't check success on the compilation or protect the call of the resulting function.

**Comment by creationix** [comment]
yeah, the autocomplete code should protect itself against crashes.  Feel free to send a PR adding this.
