### ISSUE TITLE
Luvit API Documentation link returns a 404

### ISSUE THREAD

**Issue by leonardus** [luvit/luvit#1036]
The link on [this page](https://luvit.io/docs.html) that says "Luvit API Documentation" returns a 404.
It is a link to https://luvit.io/api/.

**Comment by SinisterRectus** [comment]
I'm not sure what's going on here. Issues for the website go on https://github.com/luvit/luvit.io though.

**Comment by creationix** [comment]
New issue https://github.com/luvit/luvit.io/issues/25
