### ISSUE TITLE
Socket callback

### ISSUE THREAD

**Issue by Lautenschlager-id** [luvit/luvit#1051]
Regarding the callback we provide on `Socket:connect`, shouldn't this chunk:
###### ref [net#L214](https://github.com/luvit/luvit/blob/master/deps/net.lua#L214)
```Lua
self:emit('connect')
if callback then callback() end
```

be

```Lua
if callback then callback() end
self:emit('connect')
```

?

From my understanding, we should be able to set the event callbacks (:on) inside this callback, and since it's called after one emit we miss it.

I'm currently using `net.createConnection` and doing something like the chunk below is currently impossible, I assume.
```Lua
local socket
socket = net.createConnection(port, ip, function()
	socket:on("connect", function()

	end)
end)
```

I would PR it but I'm not sure if has any specific behavior that I'm missing.

Another solution would be setting two callbacks, one before and one after :thinking:

**Comment by squeek502** [comment]
With how it's set up now, can't you assume that if `callback` gets called, then it connected? The `:on('connect'` inside the callback is redundant, right?

**Comment by rphillips** [comment]
The third parameter to net.createConnection only gets called when there is an onConnect event, so setting a `socket:on("connect", ...)` would naturally miss. 

NodeJS has something called a [tick](https://medium.com/@amanhimself/how-process-nexttick-works-in-node-js-cb327812e083). The connect emitter has already been triggered before the callback.
