### ISSUE TITLE
uv.spawn() might fail

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luvit#1055]
[uv.spawn()](https://github.com/luvit/luvit/blob/master/deps/childprocess.lua#L133) might fail, e.g. because of `ENOMEM: not enough memory`. In this case the `handle` is `nil` and the `pid` has the value of the error message.

`uv.spawn()` not returning a valid `handle` should be handled as an error and reported to the user.

**Comment by squeek502** [comment]
Similar issue from when this affected `coro-spawn`: https://github.com/luvit/lit/pull/220

**Comment by joerg-krause** [comment]
Closed, as the errors from uv.spawn() are actually handled. Not the way I thought it should be, but after studying the sources, e.g. looking at [test-process.lua](https://github.com/luvit/luvit/blob/master/tests/test-process.lua), I understand how to get the error messages.
