### ISSUE TITLE
Luvit CMD download failing.

### ISSUE THREAD

**Issue by AntwanR942** [luvit/luvit#1057]
Whenever I attempt to download luvit via the Windows Command Prompt with the command provided on Luvit.io I get this error. 

`lit version: 3.6.2
luvi version: v2.9.1
command: make lit://luvit/luvit luvit.exe luvi.exe
load config: C:\Users\antwa\AppData\Roaming\litconfig
connecting: wss://lit.luvit.io/
using snapshot: 6e805fb6a48f25304cc6553f18a01ecc30f10e30
creating binary: C:\Users\antwa\Desktop\airbus\luvit.exe
using luvi from: C:\Users\antwa\Desktop\airbus\luvi.exe
fetching: 1 object
fail: [string "bundle:libs/codec.lua"]:123: No such hash: 6e805fb6a48f25304cc6553f18a01ecc30f10e30
stack traceback:
        [C]: in function 'assert'
        [string "bundle:libs/codec.lua"]:123: in function 'read'
        [string "bundle:libs/codec.lua"]:128: in function 'readAs'
        [string "bundle:libs/rdb.lua"]:165: in function 'fetch'
        [string "bundle:libs/rdb.lua"]:140: in function 'load'
        [string "bundle:deps/git/db.lua"]:395: in function 'loadAny'
        [string "bundle:libs/pkg.lua"]:132: in function 'queryDb'
        [string "bundle:libs/core.lua"]:378: in function 'makeUrl'
        [string "bundle:commands/make.lua"]:13: in function <[string "bundle:commands/make.lua"]:1>
        [string "bundle:main.lua"]:69: in function <[string "bundle:main.lua"]:56>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:56: in function <[string "bundle:main.lua"]:48>`

**Comment by squeek502** [comment]
Relevant issues:
- https://github.com/luvit/lit/issues/247
- https://github.com/luvit/lit/issues/248

Will be addressed by https://github.com/luvit/lit/pull/250 and https://github.com/luvit/lit/pull/249

**Comment by AntwanR942** [comment]
Do you know how long this will take to be fixed? 

Thanks for the quick response!

**Comment by squeek502** [comment]
Should be fixed now. Let me know if it's working for you.
