### ISSUE TITLE
Install fails on raspberry pi

### ISSUE THREAD

**Issue by dawglazvari** [luvit/luvit#1061]
When I run the script listed for linux on my raspberry pi (running raspbian), I get a `./luvi: 1: ./luvi: Not: not found`. I tried the script on the ubuntu subsystem for linux and it worked fine. Any help?
Here's the full logs:
`pi@raspberrypi:~/luvit $ curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   127  100   127    0     0    189      0 --:--:-- --:--:-- --:--:--   189
100   567  100   567    0     0    550      0  0:00:01  0:00:01 --:--:--   550
Downloading https://github.com/luvit/luvi/releases/download/v2.9.1/luvi-regular-Linux_armv7l to luvi
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     9    0     9    0     0     22      0 --:--:-- --:--:-- --:--:--    22
Downloading https://lit.luvit.io/packages/luvit/lit/v3.7.0.zip to lit.zip
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  220k  100  220k    0     0   294k      0 --:--:-- --:--:-- --:--:--  294k
./luvi: 1: ./luvi: Not: not found`

**Comment by squeek502** [comment]
Pre-compiled armv71 binaries don't exist for the latest luvi versions (the build box that was used to compile them in the past is gone). You can self-compile [luvi](https://github.com/luvit/luvi) or use [the last version that has precompiled armv71 binaries (2.7.6)](https://github.com/luvit/luvi/releases/tag/v2.7.6).

Let me know if you need more help with either of those options.

**Comment by dawglazvari** [comment]
Thanks for your help, for anyone wanting this you just install the linux_armv7l on the url then use some of the commands from the [shell script currently in use](https://raw.githubusercontent.com/luvit/lit/master/get-lit.sh) and you'll get it fine
