### ISSUE TITLE
How to run Luvit 24/7

### ISSUE THREAD

**Issue by teddymisty132** [luvit/luvit#1068]
I want to be able to run luvit 24/7 on my VPS, so I am wondering if there is anything I can do that works like pm2.

**Comment by truemedian** [comment]
Is there anything wrong with using pm2, it's just a general process manager, but to answer your question, there has not been such a process manager written in Lua

**Comment by teddymisty132** [comment]
would pm2 work with lua?

**Comment by truemedian** [comment]
All you should need to do is tell it to run luvit instead of node

**Comment by teddymisty132** [comment]
How would I do that? Sorry, I'm not good with the whole VPS thing.

**Comment by truemedian** [comment]
You should be able to append `--interpreter=luvit` to your call to `pm2 start` and it should then use luvit as its interpreter.

**Comment by teddymisty132** [comment]
https://wumpus-said.trust-this.site/BxBN.png

**Comment by ryanford-frontend** [comment]
Here's something a little more lightweight [https://github.com/tj/mon](https://github.com/tj/mon)

**Comment by teddymisty132** [comment]
It's alright, I got pm2 working fine. For some reason the directory on my VPS wasn't registering that luvit was installed.
