### ISSUE TITLE
How to get DLL

### ISSUE THREAD

**Issue by martmists** [luvit/luvit#1072]
A program I use requires a Lua51.dll to run Lua, and I was wondering how to compile luvit to replace this file, as the code I'm trying to use only runs on Luvit which isnt supported by this version of lua.

**Comment by SinisterRectus** [comment]
Were you able to find a solution here? Luvit is not an implementation of Lua that can be compiled into a Lua dynamic library. Luvit is a pure-Lua application layer built on top of a C application that combines LuaJIT (by default) with libuv, openssl, and some others.

**Comment by martmists** [comment]
We ended up just going for regular lua due to ease of distribution
