### ISSUE TITLE
tls problems with https

### ISSUE THREAD

**Issue by ShaftBoyardee** [luvit/luvit#1080]
Whenever I try to make a get request w/ https I'm output  
```
deps/tls/common.lua:66: bad argument #1 to 'ctx_new' (only support TLS, DTLS to negotiate highest available SSL/TLS or DTLS version above openssl v1.1.0
optional followed by _client or _server
default is TLS
```

Not having any similar problems with http request, except obviously status code 301 when using https links.

**Comment by squeek502** [comment]
What's your `luvit --version` output?

**Comment by ShaftBoyardee** [comment]
Installed a fresh copy a couple days ago to make sure I wasn't out of date but this is what I'm on:
```
luvit version: 2.15.0
luvi version: v2.9.3
libuv version: 1.27.0
rex version: 8.37 2015-04-28
winsvc version: 1.0.0
ssl version: OpenSSL 1.1.1b  26 Feb 2019, lua-openssl 0.7.5
```

**Comment by squeek502** [comment]
Okay, found the issue. A new version of `luvit/tls` was never published after [this change](https://github.com/luvit/luvit/pull/1062) so OpenSSL 1.1+ is broken. Will bump/publish new deps in a bit.

Also, in your `https.request` example, `hostname` should not include `https://`. The first argument can be either a full URL as a string (like `"https://www.google.com"`) or, if you need to set other options, you should use the result of `http.parseUrl`, add options to the returned table and pass that to `request`:

```lua
local options = http.parseUrl("https://www.google.com")
options.method = 'GET'
https.request(options, function() end)
```

**Comment by ShaftBoyardee** [comment]
Gotcha. Thanks so much for your help! I kinda skimmed through the url formatting when looking at the api, haha

**Comment by squeek502** [comment]
Please update your luvit, `https` should work with OpenSSL 1.1.x with Luvit 2.16.0.
