### ISSUE TITLE
can't use the REPL or run a script

### ISSUE THREAD

**Issue by mrtnpwn** [luvit/luvit#1090]
Apparently, using the latest version, which is [v2.16.0](https://github.com/luvit/luvit/releases/tag/2.16.0), the program `luvit`, whenever is a script or trying to spawn the REPL without giving arguments, won't run because of an error:

```
/home/tim/luvi/src/lua/luvibundle.lua:321: bundle:deps/require.lua: cannot load incompatible bytecode
```

The other tools, `lit` and `luvi` work perfectly fine.

I don't know if this helps, but I will attach it here:

```
➜  ~ lit update
lit version: 3.7.3
luvi version: v2.9.3
command: update
load config: /home/mrtnpwn/.litconfig
downloading: https://lit.luvit.io/packages/luvit/lit
lit is up to date: 3.7.3
luvit is up to date: 2.16.0
luvi is up to date: v2.9.3
done: success
```

**Comment by SinisterRectus** [comment]
You can explicitly define which luvi to use to build luvit as a workaround for this. See https://github.com/luvit/lit/issues/252

**Comment by squeek502** [comment]
This should be fixed now, given that Lit is up-to-date
