### ISSUE TITLE
Luvit on non-SSE2 processor

### ISSUE THREAD

**Issue by bramroelandts** [luvit/luvit#1100]
I've been using `Luvit` for quite a while on various ARM platforms and like it a lot. I've written quite some code previously which I would like to reuse on a different platform.

Because Luvit seems so lightweight, I thought it would be no problem at all to just compile it from source on the new platform I'm working on. It is based on an `Intel Quark` (i586 with x87) processor, which does not support SSE. When compiling, however, it turned out that `LuaJIT` doesn't work with processors without SSE.

I would still like to reuse my old code on this new platform. I read that it used to be possible to use `LuaJIT` without the JIT part on older processors, but not anymore. I'm not very familiar with the insides of `Luvit`, so I was wondering what my options are here. Can I drop the JIT part and still use Luvit for its familiar APIs? How would I go about this issue?

Thanks a lot in advance and thanks for this awesome project!

**Comment by SinisterRectus** [comment]
Some of the *luvit* libraries, examples, and tests rely on LuaJIT-specific modules such as `bit`, `jit`, and `ffi`. Luvit's bindings to libuv ([luv](https://luarocks.org/modules/creationix/luv)) and other internal modules ([openssl](https://luarocks.org/modules/zhaozg/openssl), [lpeg](https://luarocks.org/modules/luarocks/lpeg)) do support other versions of Lua (5.1, 5.2, 5.3), but *luvi* (the application core and builder) is configured to use LuaJIT out of the box. It might be possible to build a non-LuaJIT version of Luvi, and there have been efforts towards this (see luvit/luvi#109), but it's not something that is officially supported. I think that right now, your best option is to use different versions of the internal modules directly. For example, you can set up a LuaRocks environment and install luv, openssl, and lpeg for Lua 5.3.

**Comment by bramroelandts** [comment]
I'll definitely look into using the various internal modules, although I did rely heavily on `bit` and also `ffi` from time to time. Thanks for the pointers!

**Comment by SinisterRectus** [comment]
You have some options for bitwise operators in Lua:

- LuaJIT's bitop module is available for Lua 5.1 and 5.2: http://bitop.luajit.org/
- Lua 5.2 has a standard library: https://www.lua.org/manual/5.2/manual.html#6.7
- Lua 5.3 has proper bitops: https://www.lua.org/manual/5.3/manual.html#3.4.2

LuaJIT's ffi is mostly unique. There is an external version of it floating around (https://github.com/facebookarchive/luaffifb), but it seems to be neglected.
