### ISSUE TITLE
Does not play nicely with more than 1 dictionaries in a dictionary

### ISSUE THREAD

**Issue by AlexHasNoFace** [luvit/luvit#1103]
I am not sure how or why this issue happens, but if you try to put 2 dictionaries in a dictionary it stops and errors because it expected the parent dictionary to close but instead you open a new one.
Sorry if this is not an issue.

**Comment by SinisterRectus** [comment]
Uhh. Can you clarify what you are doing with some sample code?

**Comment by AlexHasNoFace** [comment]
![dirlua](https://user-images.githubusercontent.com/55563754/77532559-0285f900-6e8d-11ea-9ccc-3f65dfec9571.png)
and the raw code:
local Products = {
	Item = {
		desc = "Some top quality item this is",
		alias = {"thing"},
		response = function(message, args)
			--Sends response
		end
	}
	EpicThing = {
		desc = "Some ultra quality item this is",
		alias = {"coolerthing"},
		response = function(message, args)
			--Sends response
		end
	}
}

print(Products.Item.desc)

**Comment by SinisterRectus** [comment]
You have a syntax error. You need to separate each table element with a comma (or semi-colon). Put one at the end of line 4.

**Comment by AlexHasNoFace** [comment]
Oh, I feel really stupid now. Thanks.
