### ISSUE TITLE
There is no body in http request

### ISSUE THREAD

**Issue by mawesome4ever** [luvit/luvit#1121]
I have the following code: 
```
http.createServer(function (req, res)
    print(req.body)
}
```
but it returns nil. After looping through req i see the follow: 
![image](https://user-images.githubusercontent.com/26739505/88419997-fce8e300-cd9a-11ea-8e5b-60d7dcbfaa53.png)

As you may see, there's no body. Also, what's with the documentation not having any descriptions of anything or at least any examples? https://luvit.io/api/http.html

**Comment by truemedian** [comment]
luvit's builtin `http` library is a port of the nodejs `http` library, which is almost entirely callback oriented. To get the request body you need to use `req:on('data', fn)` and `req:on('end', fn)` to capture (and probably buffer) the request body.

As for the other question: the luvit documentation is not maintained whatsoever and most things just don't have documentation.

**Comment by mawesome4ever** [comment]
Oh that makes sense! Just looked at nodejs [wiki page](https://nodejs.org/es/docs/guides/anatomy-of-an-http-transaction/) and it helped, thanks!
