### ISSUE TITLE
no jit is ok?

### ISSUE THREAD

**Issue by 947942434** [luvit/luvit#1132]
use lua5.4 not jit

[string "bundle:deps/require.lua"]:278: No such module 'jit' in 'bundle:/deps/los.lua'
module 'jit' not found:
        no field package.preload['jit']
        no file 'C:\Lib\luvit\lua\jit.lua'
        no file 'C:\Lib\luvit\lua\jit\init.lua'
        no file 'C:\Lib\luvit\jit.lua'
        no file 'C:\Lib\luvit\jit\init.lua'
        no file 'C:\Lib\luvit\..\share\lua\5.4\jit.lua'
        no file 'C:\Lib\luvit\..\share\lua\5.4\jit\init.lua'
        no file '.\jit.lua'
        no file '.\jit\init.lua'
        no file 'C:\Lib\luvit\jit.dll'
        no file 'C:\Lib\luvit\..\lib\lua\5.4\jit.dll'
        no file 'C:\Lib\luvit\loadall.dll'
        no file '.\jit.dll'
stack traceback:
        [C]: in function 'error'
        [string "bundle:deps/require.lua"]:278: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)
        [string "bundle:/deps/los.lua"]:28: in local 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)
        [string "bundle:/deps/path/init.lua"]:19: in local 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)
        [string "bundle:/deps/fs.lua"]:35: in local 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)
        [string "bundle:/deps/dns.lua"]:40: in local 'fn'
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)
        [string "bundle:/init.lua"]:33: in function <[string "bundle:/init.lua"]:20>
        (...tail calls...)
        [string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
        (...tail calls...)

**Comment by SinisterRectus** [comment]
Some Luvit libraries depend on LuaJIT libraries like `jit` and `ffi`. There is no supported non-LuaJIT version of Luvit.

**Comment by 947942434** [comment]
use ffi + lua5.4 compat 5.1 but require('dns') is error !

dns model whereis ?

**Comment by squeek502** [comment]
https://github.com/luvit/luvit/blob/master/deps/dns.lua
