### ISSUE TITLE
angry okda

### ISSUE THREAD

**Issue by noaccessl** [luvit/luvit#1134]
ну как бы вы моему знакомому жизнь испортили окда? вот вы написали вики? написали, а как? правильно - на коленке, никаких описаний к встроенным модулям, просто функция( аргумент1, аргумент2 ). Великолепно! Я всё замечательно понял!
Закрывайте исуе мне от балды :sunglasses:

**Comment by Natives3000** [comment]
english please and the built in modules docs are the same as nodejs built in so you can go on nodejs website and see docs for it

**Comment by TGoldenB** [comment]
Ну это только ты. Кто не умеет правильно читать документы! проверьте https://luvit.io
Печально, что ты пытаешься срать пост без причины.

Google translate for win.
