### ISSUE TITLE
Luvit Running

### ISSUE THREAD

**Issue by DumpBotDeveloper** [luvit/luvit#1136]
I recently installed **luvit** as the correct way, my friend and me have issues with the **running** or something.
![Issue](https://user-images.githubusercontent.com/74837790/108386898-b3e2fb00-71d2-11eb-80ef-bac7da35ca46.png)

System type: 32-bit Operating System, x64 based processor

**Comment by truemedian** [comment]
Luvit is running correctly. You just haven't saved the changes you've made to that file.

**Comment by DumpBotDeveloper** [comment]
I think i'm stupid, thanks
