### ISSUE TITLE
Unable to go to luvit.io

### ISSUE THREAD

**Issue by ManyFoxes** [luvit/luvit#1137]
So I'm setting up on a ubuntu vm to run a bot, and when i got to luvit.io it gives me a 504 error.

**Comment by SinisterRectus** [comment]
We're aware, it will be fixed first chance we get. If you are just looking to set up luvit and lit, use install instructions at https://github.com/luvit/lit#installing-lit.

**Comment by SinisterRectus** [comment]
Should be fixed now.
