### ISSUE TITLE
Uncaught Error: [string "bundle:/deps/net.lua"]:139: attempt to call local 'callback' (a string value)

### ISSUE THREAD

**Issue by Devieth** [luvit/luvit#1198]
Not exactly sure what is causing this error. I believe it is when I make a http get/post request (while running an https server) but there is no reply because the external server is down or not responding?  Sorry I do not have more details.

```
Uncaught Error: [string "bundle:/deps/net.lua"]:139: attempt to call local 'callback' (a string value)
stack traceback:
        [string "bundle:/deps/net.lua"]:139: in function <[string "bundle:/deps/net.lua"]:137>
        [C]: in function 'run'
        [string "bundle:/init.lua"]:55: in function <[string "bundle:/init.lua"]:47>
        [C]: in function 'xpcall'
        [string "bundle:/init.lua"]:47: in function 'fn'
        [string "bundle:deps/require.lua"]:310: in function <[string "bundle:deps/require.lua"]:266>
 ```

**Comment by PatrickDahlin** [comment]
To me this looks impossible to debug without any more code or info about the repro-case. Are you using weblit, net sockets or the http library?

**Comment by Devieth** [comment]
Solution is to just use a proper timeout when making a request, sorry should have came back and close this.  Thank you anyway.
