### ISSUE TITLE
net.lua - No callback on connection errors

### ISSUE THREAD

**Issue by d4rkmen** [luvit/luvit#1199]
When its connection error happened and it should call the callback with error message, it just closes the handle silently

Here it should pass the `callback` to destroy():

https://github.com/luvit/luvit/blob/a8c708e064cc1d60ecca8d8ca00bc28fa2e49eeb/deps/net.lua#L228

And here is should pass the exception to the `callback`
https://github.com/luvit/luvit/blob/a8c708e064cc1d60ecca8d8ca00bc28fa2e49eeb/deps/net.lua#L262

**Comment by PatrickDahlin** [comment]
If you take a look at line 268 in that same file, it'll emit an 'error' event since the parameter "exception" will be truthy.

Besides, regardless if the handle is closing, it'll call callback function from 258 or 262.

Minimal sample code for a repro always helps more than just pointing at a line and say error.

**Comment by d4rkmen** [comment]
Here we go the `tcp-echo-client-simple.lua` slightly changed:

```lua
local net = require('net')

local client
client = net.createConnection(12345, '127.0.0.1', function (err)

  if err then error(err) end

  print("Connected...")

  -- Send stdin to the server
  process.stdin:on("data",function(data) -- or 'process.stdin:pipe(client)'
    client:write(data)
  end)

  -- Send the server's response to stdout
  client:on("data",function(data) -- or 'client:pipe(process.stdout)'
    process.stdout:write(data)
  end)

  -- Error handler
  client:on("error",function(err)
    print("error: " .. err)
    client:close()
  end)
  
end)
```

No error message in case the target name not resolved or the port is not connected
Actually, there will be only client read errors being handled

**Comment by Bilal2453** [comment]
There will be if you have assigned one to `client` at said stage. In this code example, you are just assigning the error handler way too late:

```lua
local client = net.createConnection(12345, '127.0.0.1', function(err)
  -- ...
end)
client:on("error", function(err)
  print("error: ", err) -- example: ECONNREFUSED
end)
```

**Comment by d4rkmen** [comment]
@Bilal2453 thanks, now it works. closing

**Comment by Bilal2453** [comment]
no worries.. only took me a year to answer this, sorry for the little delay there!
