### ISSUE TITLE
require('string.buffer') fails

### ISSUE THREAD

**Issue by TypedLambda** [luvit/luvit#1210]
In the luvit repl loading the LuaJIT string buffer library fails.

```
require('string.buffer')
```

I could not figure out how to require it in luvit. Works fine in a luvi application.

**Comment by SinisterRectus** [comment]
Can you share more information about the environments in which you are trying this? Luvit and luvi version numbers is a good start.

**Comment by truemedian** [comment]
For completeness, the `string.buffer` library was introduced when LuaJIT was updated for Luvi 2.14.0, it will not be present in any version of Luvi prior to 2.14.0, or any application (such as Luvit) built with a version of Luvi prior to 2.14.0

**Comment by SinisterRectus** [comment]
That'll do it.

I'm not sure if `lit update` will rebuild luvit if it detects an old version of luvi. If not, rebuild a new copy of luvit via the get-lit script on https://luvit.io. That should give you a fresh copy of luvit bundled with an updated luvi according to https://github.com/luvit/lit/pull/315.

**Comment by TypedLambda** [comment]
I built everything from scratch, and did not realize that lit would use a prebuilt livi when building luvit.
Adding my current luvi to the lit make command solves that.

Thanks a lot for helping out!
