### ISSUE TITLE
Add async ldap

### ISSUE THREAD

**Issue by miko** [luvit/luvit#134]
Hello, it would be nice to add async ldap support. One candidate to consider is to port http://ldapjs.org

**Comment by devurandom** [comment]
@miko Did you build or find a module that does this?

**Comment by creationix** [comment]
btw, I have docs for creating binary modules with the new lit/luvit 2.0 system on the lit wiki https://github.com/luvit/lit/wiki/Publishing-Compiled-Code

**Comment by miko** [comment]
@devurandom No I did not, but if I was to do it I surely would go the new luvit 2.0 way!
