### ISSUE TITLE
Add event for uncaught errors

### ISSUE THREAD

**Issue by creationix** [luvit/luvit#15]
We need a fallback way to handle uncaught errors so the server can shut itself down cleanly.  Also all errors need to be properly routed to the right place in luvit core and uncaught errors need to show meaningful stack traces.  No more silent exits.

**Comment by creationix** [comment]
I decided that at the luv level, it should hard-crash the process if there is an uncaught error in a libuv callback.  This leaves libuv in an inconsistent state.  It's up to the higher-levels to wrap all event sources in pcall or xpcall and route the error as desired.

**Comment by philips** [comment]
Close it?
