### ISSUE TITLE
msvc2010 can not build with /MDd or /MD on windows 7

### ISSUE THREAD

**Issue by zx9597446** [luvit/luvit#160]
looks like luvit's buffer module is broken on windows,  because luajit's ffi use libc as dll by default(/MDd or /MD),  but luvit's default build is /MT or /MTd,  when change luvit build with /MDd or /MD, shows error:
libluvit.lib(lenv.obj) : error LNK2001: unresolved external symbol _environ

in lenv.c(41) extern char **environ;
change to extern char **wenviron; 
can solve error,  don't know how to write a protable way to fix the problem.

from msdn:
Polling _environ in a Unicode context is meaningless when /MD or /MDd linkage is used. For the CRT DLL, the type (wide or multibyte) of the program is unknown. Only the multibyte type is created because that is the most likely scenario.

**Comment by creationix** [comment]
The new buffer module is luajit ffi based and the old C build system is replaced and reimplemented in luvi.  Closing this issue.
