### ISSUE TITLE
implement a fixed length read method or add an example deframing tcp packets

### ISSUE THREAD

**Issue by zx9597446** [luvit/luvit#164]
Tim Caswell saids he implemented a deframer like this for nodejs, but it's javascirpt,  please port it to luvit
http://www.google.com/url?sa=D&q=https://github.com/c9/remoteagent-protocol/blob/master/lib/socket-transport.js%23L54-92&usg=AFQjCNFTIn77d-0EnyxY6Bb3XOv_-i9S8w

**Comment by creationix** [comment]
There are many examples of this in the luvit/lit project.  But I'll add a couple more simple examples using the new "decoder" style.

In this style, parsers take a string as input and either return nothing (more input is needed) or return an event followed by the leftocer data.  It's the responsibility of the consumer to concatenate inputs and reuse the leftover data.

Example decoder for a newline delimited protocol.

```lua
local function deline(chunk)
  local n = chunk:find("\n", 1, true)
  -- If there is no newline yet, wait for more data
  if not n then return end
  -- Return the line and the leftover data
  return chunk:sub(1, n - 1), chunk:sub(n + 1)
end
```

Example decoder wanting fixed length chunks

```lua
local function 4byte(chunk)
  if #chunk < 4 then return end
  return chunk:sub(1, 4), chunk:sub(5)
end
```

Consuming either of these is fairly simple as well.

```lua
local buffer = ""
stream:read_start(function (err, data)
  assert(not err, err)
  if not data then
    -- end of stream
    return
  end
  buffer = buffer .. data
  local event, extra = decoder(buffer)
  if event then
    buffer = extra
    -- TODO: emit event
  end
end)
```
