### ISSUE TITLE
reliable write()

### ISSUE THREAD

**Issue by dvv** [luvit/luvit#21]
Hi!

Please, consider using something like https://github.com/dvv/sockjs-luvit/blob/master/response.lua#L219-270 to make write() reliable. May be even borrow drafts of queue impl from node.

W/o reliable write(), sending lenghty (>TCP_SND_BUFFER) messages will always be subject to subtle failures.

TIA,
--Vladimir

**Comment by creationix** [comment]
The new streams in luvit 2.0 should handle this case better.
