### ISSUE TITLE
Build option to use lua interpreter

### ISSUE THREAD

**Issue by mirkokiefer** [luvit/luvit#219]
Introduce a build option to build luvit with the lua interpreter.

**Comment by creationix** [comment]
[Luv](https://github.com/luvit/luv) can be used now with any lua backend.  It's even published to luarocks.  [Luvi](https://github.com/luvit/luvi) (the C base of luvit) is hard-coded to luajit and isn't going to change.

**Comment by creationix** [comment]
See also #682
