### ISSUE TITLE
using Luvit as a library

### ISSUE THREAD

**Issue by mirkokiefer** [luvit/luvit#220]
I would be grateful for any instructions on how to build Luvit as a static library.
Also any hints on how to properly initialize the lua_State with all required dependencies are welcome!

**Comment by creationix** [comment]
In the new luvit 2.0 system, luvit is a lit library.  An example of how to embed it can be seen in the new virgo-base-agent https://github.com/virgo-agent-toolkit/virgo-base-agent/tree/luvi-up

**Comment by creationix** [comment]
There is also an official example of how to embed luvit in a custom luvi app in the luvit examples https://github.com/luvit/luvit/tree/master/examples/custom-binary
