### ISSUE TITLE
close function is nil for TCP connection

### ISSUE THREAD

**Issue by kengonakajima** [luvit/luvit#225]
now a tcp client doesn't have close() function, so I have to use uv_native.close for actively closing the connection from client.

    native = require("uv_native")
    cl = net.createConnection(port,addr,function(err)
      cl:close() -- => gives error ( cl.close is nil)
      native.close( cl._handle ) -- => no error
    end)

Why client TCP doesn't have close()  ?    I think we need active close()ing is necessary for making TCP apps for example SMTP client. In SMTP, we have to close from client after "221 Bye".  TCP connection (or any streams) should simply have close function for ease of use.

Look at this SMTP client code line 40:
https://github.com/kengonakajima/snippets/blob/master/luvit/mailer.lua

**Comment by creationix** [comment]
In the [luv](https://github.com/luvit/luv) bindings used by luvit 2.0, all handle instances have a `:close` method now.
