### ISSUE TITLE
base64 in buffer?

### ISSUE THREAD

**Issue by yields** [luvit/luvit#234]
in node you can do `new Buffer(str, 'base64')`, why doesn't luvit's Buffer support this ?

also any thoughts on adding `Buffer` and `table` to `_G` ?

**Comment by james2doyle** [comment]
**resurrecting for luvit >= 2.7.0*

I'm actually dealing with this right now. I am trying to make a base64-safe URL encode module. There are [some slice methods](https://github.com/nodejs/node/blob/0ed3a7c11b4031bdb56908b16f2aa5aea24c1813/src/node_buffer.cc#L502-L529) that exist in node that aren't replicated here.

Not really sure about the impact for this feature request.

**Comment by zhaozg** [comment]
It's ancient, so close.
