### ISSUE TITLE
[RFC] Replace all build system with cross-platform Cmake

### ISSUE THREAD

**Issue by xming** [luvit/luvit#251]
I have done some work to initial Cmake build system for luvit, Cmake is cross-platform and should be able replace all the different build system we have now.

what is working right now:

- only building against system http_parse, libuv, zlib, openssl, yajl and luajit
- automatically search the includes/libs
- compile time feature selection of http_parse, zlib, openssla and yajl (with this patch https://github.com/luvit/luvit/issues/250)
- bundled or non bundled build
- tools/bundle.lua is eliminated, we don't need temporary luvit build just to be able to run bundle.lua

what need to be done:
- other platform (non Linux/Unix) testing, I don't know how cmake works on windows
- build in deps d/l, unpack, prepare, compile (see below for RFC), this can all be done with our cmake regardless what beuild system those deps use
- easy to add you own modules (either c and/or lua) to be build into lua and bundled (see below for RFC)
- remove all other build system

fix build bugs, add build features like in 
- https://github.com/luvit/luvit/issues/220
- https://github.com/luvit/luvit/pull/233
- https://github.com/luvit/luvit/issues/219
...

RFC:
- anyone has remarks/comments for/against cmake?
- should this work be continued?
- for deps, should be offer stable versions (included in the luvit tarball) and git? IMHO offer stable tar/zip in luvit can futher decrease the dependencies to build, my goal is that only cmake/compiler/linker/assembler are needed to build luvit, git version would then be for more advanced users.
- for modules (we have 4 now http_parse, zlib, openssla and yajl) I am thinking of a directory structure, something like

```
luvit/
  src/
  modules/
    MyOwnModules/
      src/ -> where all the .c/.h go
      lua/ -> for .lua
      CmakeList.txt -> template should be provided for how to do this
```

so making a own module for luvit (for to be linked and bundled) becomes easy. Does this sound good?

You can get a feel of cmake with this test tarball https://github.com/downloads/xming/luvit/luvit.cmake-test.tgz although you will need luajit install (optional http_parser, openssl en yajl installed if you choose these features).

**Comment by creationix** [comment]
We ended up redoing the build system from the ground up.  The new system is indeed using cmake for the luvi component.  Luvit itself is pure lua and doesn't need anything other than luvi or lit.
