### ISSUE TITLE
"make bundle" is cross-compile unfriendly

### ISSUE THREAD

**Issue by dvv** [luvit/luvit#253]
make bundle requires host luvit (deps/luajit/src/luajit, to be precise). naturally, it's not possible to build bundle for another arch. nor it's possible to make deps/luajit/src/luajit consistently (again, host buildvm needed)

**Comment by creationix** [comment]
We have a new build system.  If you want to add cross-compile into the new cmake system I think it may still have this problem cross-compiling luvi.  File a new issue there if you need to.
