### ISSUE TITLE
[Doc] how to create a module for luvit?

### ISSUE THREAD

**Issue by hnakamur** [luvit/luvit#261]
I would like a document about:
* how to create a module for luvit.
* how to install a module

Maybe in wikipages in the luvit github repository?

**Comment by creationix** [comment]
I just wrote a wiki page about how to create binary addons and publish/consume them using lit at https://github.com/luvit/lit/wiki/Publishing-Compiled-Code

More docs to come.

**Comment by creationix** [comment]
The metadata format is documented at https://github.com/luvit/lit/wiki/Package-Metadata

**Comment by creationix** [comment]
A tutorial is now at https://github.com/luvit/lit/wiki/Creating-Your-First-Package
