### ISSUE TITLE
http request doesn't emit end from HTTP/1.0 server

### ISSUE THREAD

**Issue by tim-smart** [luvit/luvit#267]
Doing some last.fm api stuff for a small tool that gets the currently playing track. Currently running into an issue where the end event is not being emitted.

See https://gist.github.com/3021609 (working from the querystring.stringify branch) for a reproducible test case.

**Comment by creationix** [comment]
I think this is fixed with the new http-codec library used in luvit 2.0.  Please re-test.

**Comment by tim-smart** [comment]
Retested and ran into an issue where the response event isn't being emitted: #664

**Comment by tim-smart** [comment]
Moved the callback to the second argument of `http.request`, seems to work great but the event loop sits on idle after everything finishes. I expected it to exit the program!

**Comment by creationix** [comment]
@tim-smart maybe it's a keepalive connection?  We didn't clone the entire agent behavior from node's http API.  Can you share your example?

**Comment by tim-smart** [comment]
Here is a gist:
https://gist.github.com/9727132763b264051fa8

**Comment by creationix** [comment]
I see.  I wonder what node does.  Perhaps we can uv.unref the connection while it's idle and then ref it again if it's used again.  We already close all active handles on process exit.

**Comment by rphillips** [comment]
hmm ```uv.walk(p)``` does not show an active tcp handle

**Comment by tim-smart** [comment]
Created a new issue, will close this one as the `end` event is now working fine! Thanks
