### ISSUE TITLE
alternate timer api

### ISSUE THREAD

**Issue by coolaj86** [luvit/luvit#280]
Since timer doesn't keep the same API as javascript anyway and the token isn't even an int, it would make more sense for start / stop to be part of the object.

    t = timer:new(fn)
    -- if initialDelay is nil, this is just a setInterval
    -- if repeatInterval is nil, this is just a setTimeout
    -- if both are a number the interval starts after the delay
    t.start(initialDelay, repeatInterval)
    t.stop()

This would solve a number of existing annoyances in setTimeout / setInterval.

**Comment by creationix** [comment]
The libuv API can be used directly now in [luv](https://github.com/luvit/luv).

So from luvit, a serinterval can be done with:

```lua
local uv = require('uv')

local timer = uv.new_timer()
timer:start(100, 100, function ()
  -- every 100 ms
)
timer:stop()
timer:close()
-- etc...
```
