### ISSUE TITLE
Coding conventions: we should switch to camelCase for modules

### ISSUE THREAD

**Issue by hnakamur** [luvit/luvit#294]
https://github.com/luvit/luvit/wiki/Coding-Conventions
says "DO use TitleCase for classes, modules and namespaces"

However, node.js and lua uses camelCase for modules.

Currently, there are camelCase and TitleCase modules in luvit source code.
For example,
examples/linux-joystick.lua:local Bit = require('bit')
lib/luvit/buffer.lua:local bit = require('bit')
Inconsistencies.

TitleCase module names are unfamiliar.
So we should switch to camelCase module names in luvit.

**Comment by creationix** [comment]
I prefer camelCase for module exports.  I believe most the new code in luvit 2.0 does this.
