### ISSUE TITLE
[API] Make fs.write take same arguments as node.js

### ISSUE THREAD

**Issue by hnakamur** [luvit/luvit#314]
By looking tests in #313, you find the current version of fs.write in Luvit has the signature:
fs.write(fd, offset, buffer, callback)
fs.writeSync(fd, offset, buffer)

However, fs.write in node.js has the signature:
fs.write(fd, buffer, offset, length, position, [callback])
fs.writeSync(fd, buffer, offset, length, position)
http://nodejs.org/api/fs.html#fs_fs_write_fd_buffer_offset_length_position_callback

We should make fs.write in Luvit take same arguments as node.js to make porting from node.js to Luvit easier.

**Comment by zhaozg** [comment]
It's ancient, so close.
