### ISSUE TITLE
process.stderr is truncated out when crash

### ISSUE THREAD

**Issue by kengonakajima** [luvit/luvit#342]
This code will cause an error and luvit quits as expected, but I can't get output of stderr at all.

    for i=1,10 do
      process.stderr:write( "xxxxxxx:" .. i .. "\n")
    end
    func_not_def()

    bash $ luvit  test_code_above.lua  > logfile 2>&1

stderr uses SyncWriteStream, but is it buffered?

it is not buffered when luvit is invoked from tty. It only truncates only when stdout or stderr is to files.

**Comment by rphillips** [comment]
seems to be fixed in 2.0
