### ISSUE TITLE
examples/fs-watchfile.lua: Assertion `lhandle->refCount' failed.

### ISSUE THREAD

**Issue by ackalker** [luvit/luvit#367]
When trying to run this example with latest Git,  creating a file `bar` from another termina, I get the following assertion hit:
```
$ out/Debug/luvit examples/fs-watchfile.lua
{ handlers = { change = table: 0x407a3a40 }, userdata = userdata: 0x407a38c8 }
luvit: ../src/utils.c:268: luv_handle_get_lua: Assertion `lhandle->refCount' failed.`
```
Getting a backtrace from GDB looks like this: https://gist.github.com/4141041

Hope this helps,

Alain

**Comment by rphillips** [comment]
should be fixed in 2.0
