### ISSUE TITLE
specifying alternative LIBDIR will break module loading

### ISSUE THREAD

**Issue by hasufell** [luvit/luvit#379]
I have no clue about lua, so cannot attach any code.

But the paths where "module.lua" looks for are more or less hardcoded (it expects /usr/lib/luvit). The LIBDIR variable which can be overwritten at build time should be added to the locations where it looks for the modules.

This is also important for systems where we want real libsuffix support like lib64 vs lib32.

**Comment by creationix** [comment]
Obsoleted by new build system in luvit 2.0
