### ISSUE TITLE
Did Luvit support WSAPI

### ISSUE THREAD

**Issue by MarkTseng** [luvit/luvit#391]
Did Luvit support WSAPI? or how to create CGI

**Comment by creationix** [comment]
@MarkTseng I'm cleaning out old issues getting ready for luvit 2.0.  Do you still care about using luvit with WSAPI?

To answer your last question, yes, luvit is the same as node, it is a standalone http server.  There is no existing library to act as wsapi server or client that I know of.

Re-open if you have further questions or problems.
