### ISSUE TITLE
Git clone instructions at http://luvit.io/ are incorrect

### ISSUE THREAD

**Issue by RossBencina** [luvit/luvit#395]
http://luvit.io/ 

Under "Installation from Source, From git"

> git clone https://github.com/luvit/luvit.git

Should be:

git clone https://github.com/luvit/luvit.git --recursive

Note that the correct command (with --recursive) is given in the README.markdown

**Comment by creationix** [comment]
Closing in favor to #658.  Luvit itself it about to migrate to luvi and thus no longer has submodules, but uses lit to built itself via the get-lit script.
