### ISSUE TITLE
configure.py gives incorrect build instructions

### ISSUE THREAD

**Issue by RossBencina** [luvit/luvit#396]
Configure.py gives wrong instructions at the end of configuring. Here's an example session:

......
<pre>
>python configure
[snip]

Done!

Now run `python build.py` to build!

> python build.py
python: can't open file 'build.py': [Errno 2] No such file or directory
</pre>
......

Configure.py should be edited to say:

Now run `python tools/build.py build` to build!

**Comment by creationix** [comment]
The build system is now cmake based for luvi and pure luvi/lit for everything above that.  See details at new luvit.io site.
