### ISSUE TITLE
Neither http://luvit.io/ nor the website give correct build instructions for Windows

### ISSUE THREAD

**Issue by RossBencina** [luvit/luvit#397]
No instructions are provided for building with gyp (ie without the Makefile). In other words: no instructions are provided for building on Windows.

Both the website and README.markdown should be updated.

Here are some instructions that seem to work for me on Windows with MSVC2010SP1 (commercial). Both the tarball and git instructions seem to work except that the tarball gives linker errors.
.......

Installation from Source (Windows)

Note that you need to have Python, a compatible version of Visual Studio and possibly the Windows platform SDK installed (and also git for git-based installation).

From git:
<pre>
> git clone https://github.com/luvit/luvit.git --recursive
> cd luvit
> python configure
> python tools/build.py build
</pre>
and then to run the tests:
<pre>
>python tools/build.py tests
</pre>

From the tarball:

Download the latest tarball.

First, uncompress and untar the tarball. You can use a utility like 7zip or gnu command line tools if you have them installed.

<pre>
> gunzip luvit-0.6.0.tar.gz
> tar xvf luvit-0.6.0.tar
> cd luvit-0.6.0
> python configure
> python tools/build.py build
</pre>

.......
These instructions appear to make 32 bit builds. They put the built files in ./Debug. I don't know how to specify a release build from the command line -- that should be documented.

Note that the 0.6 tarball does not currently build (at least on my MSVC2010SP1 setup).

I'm not sure how to make 64-bit builds. The following post suggests `set GYP_DEFINES=target_arch=x64` however that doesn't seem to work.

https://groups.google.com/forum/#!msg/luvit/gDD1lhNSYNQ/Pbwn3OIYNIYJ

**Comment by creationix** [comment]
We're in the process of releasing luvit 2.0 which has a much easier build system for windows.  See instructions at the new luvit.io website.
