### ISSUE TITLE
Add support for sqlite

### ISSUE THREAD

**Issue by Dialga** [luvit/luvit#426]
It would be nice to have builtin support for sqlite databases.

**Comment by nihildeb** [comment]
@creationix I need this too, and I think I will do it. It should be done as a binary lit package though right? I am actually leaning towards the idea of route/sqlite/lmdb but building lmdb for windows sounds like it might be trouble, we'll see. 

Anyway, i guess the approach is to build bins and use the existing luajit ffi module. Luvit supports Lua vanilla 5.2 and 5.3 too, how should that work? Should I just name it sqlite3-ffi (i am not really interested in supporting multiple OSs and multiple Luas. Luajit on win/linux/osx is more than enough I think.

**Comment by creationix** [comment]
I have a few examples of publishing modules to lit that use ffi bindings.

 - https://github.com/creationix/lit-hoedown
 - https://github.com/creationix/lit-gamepad

The interesting bit is this line in package.lua:

https://github.com/creationix/lit-gamepad/blob/master/package.lua#L13

When you publish to lit, it will include all the different binaries.  I commit the binaries to github as well.  But when someone installs your package as a dep to their app, it will only include the binary that matches their platform and machine.

I also wrote a wiki page with some more tips and ideas. https://github.com/luvit/lit/wiki/Publishing-Compiled-Code

**Comment by nihildeb** [comment]
@creationix hey, i am running into a little trouble with callbacks and sqlite C API, and I saw in the Lua mailing list you posted a problem similar to mine. If you have a sec, could you have a look at this and tell me if anything pops out at you (you seem to have solved the callback issue well :)

http://stackoverflow.com/questions/30032225/expected-eof-from-ffi-cast-in-luajit

Thanks!

**Comment by creationix** [comment]
I generally avoid callbacks in luajit ffi.  They are slow and don't seem very stable.  But it appears someone helped with your SO question already.

**Comment by nihildeb** [comment]
@Dialga  
Published! Tests are currently not running. I moved them into the sample project at the last minute, but it's pretty well tested, and they were running before I moved them.

Initial release is Linux only. I'll be building the other bins today probably.
https://github.com/nihildeb/lit-sqlite3-sample

@creationix - thanks for your help and links, the examples helped a lot!
