### ISSUE TITLE
string interning aka lua_tolstring is slow

### ISSUE THREAD

**Issue by cyisfor** [luvit/luvit#450]
When reading stuff from the net or files, should use a different structure than lua strings. Using strings as buffers messes up interning lookup tables, and wastes time with multiple redundant buffer copy/compares for every lua_pushlstring.

So I made this: https://github.com/cyisfor/lua_buffer/

Would love to have luvit use it, or something similar.

test.lua works on 8/8, but needs minitest and (not really) fancyRequire.
https://github.com/cyisfor/lua_minitest/
https://github.com/cyisfor/lua_fancyrequire/
anything else (luassert) should be up on luarocks.

**Comment by creationix** [comment]
Closing for now.  Reopen if there is something we should do in luvit.
