### ISSUE TITLE
os.execute and sandboxing

### ISSUE THREAD

**Issue by darkFunction** [luvit/luvit#460]
``` lua
_G.os = require("os")
os.execute("ls")  -- attempt to call field 'execute' (a nil value)
```

I'm not able to run os.execute from luvit... Is there a security reason for this? Also, is there a way around it? I'm running an intranet only site and would like to launch scripts from the luvit server directly without going down the php/cgi route. 

Love this project btw - good work!

**Comment by prashantabmc** [comment]
Can we execute os.execute() command when using luvit ?

**Comment by creationix** [comment]
@prashantabmc you can, but it will block the main thread and pause the event loop.  So don't do it in any server that handles concurrent requests.  They will *all* block.

**Comment by prashantabmc** [comment]
@creationix  I have a requirement to know the pid of a given process. If I can't run os.execute(), then how can I achieve the same ? Please help me.

**Comment by squeek502** [comment]
@prashantabmc 

```
local spawn = require('childprocess').spawn

local child = spawn("path/to/executable")
print(child.pid)
```

See also the 'childprocess' documentation: https://luvit.io/api/childprocess.html
Examples of using `spawn` can be found in the tests: https://github.com/luvit/luvit/blob/master/tests/test-process.lua#L32-L166

**Comment by creationix** [comment]
Also the raw uv interface allows spawning directly if you don't want to use the node-style spawn interface.

```lua
local uv = require 'uv'

local child, pid
child, pid = uv.spawn("sleep", {
  args = {"100"}
}, function (code, signal)
  p("EXIT", {code=code,signal=signal})
  uv.close(child)
end)

```
