### ISSUE TITLE
why i can't require file

### ISSUE THREAD

**Issue by yangzhu6263736** [luvit/luvit#527]
![image](https://cloud.githubusercontent.com/assets/1215298/4988249/9ac84ca6-699b-11e4-82c4-a7f34ae7ee51.png)
local JCSConst = require("Const.JCSConst")
![image](https://cloud.githubusercontent.com/assets/1215298/4988256/adb3dcf4-699b-11e4-9954-879584d73b6a.png)
/usr/local/lib/luvit/luvit.lua:309: /usr/local/lib/luvit/module.lua:193: Failed to find module 'Const.JCSConst'
        Cannot find module /usr/local/lib/luvit/Const.JCSConst
        Cannot find module /var/www/quick-x-server/SCombat/modules/Const.JCSConst
        Cannot find module /var/www/quick-x-server/SCombat/node_modules/Const.JCSConst
        Cannot find module /var/www/quick-x-server/modules/Const.JCSConst
        Cannot find module /var/www/quick-x-server/node_modules/Const.JCSConst
        Cannot find module /var/www/modules/Const.JCSConst
        Cannot find module /var/www/node_modules/Const.JCSConst
        Cannot find module /var/modules/Const.JCSConst
        Cannot find module /var/node_modules/Const.JCSConst
        Cannot find module /modules/Const.JCSConst
        Cannot find module /node_modules/Const.JCSConst

**Comment by creationix** [comment]
Luvit's require isn't an include you have to create the local references when loading external code.

For example:

```lua
local class = require('QuickFramework/functions').class
```

Luvit 2.0 is out now, let me know if you have further questions.  I'd love to help you.
