### ISSUE TITLE
Build instructions on website do not work

### ISSUE THREAD

**Issue by rmbishop** [luvit/luvit#575]
I ran the following instructions

git clone https://github.com/luvit/luvit.git --recursive
cd luvit
git submodule update --init --recursive

Once I got to the following step, I encountered an error:

./configure

There is no file named configure in the luvit directory.

**Comment by creationix** [comment]
The instructions on the website are for the master branch.  I guess since I set the `luvi-up` branch as default on github, it's also default for cloning.

Either checkout master explicitly and use the old instructions or wait for luvit 2.0 to be finished.  Sorry for the trouble.

**Comment by creationix** [comment]
Update website with new instructions.
