### ISSUE TITLE
Building with Make does not include the lib/luvit libraries

### ISSUE THREAD

**Issue by rmbishop** [luvit/luvit#576]
If I build luvit by typing Make, it generates a luvit binary that is incapable of running http server example on the following page: https://github.com/luvit/luvit.

It cannot find the http lua file that it tries to require.

**Comment by creationix** [comment]
Correct, the luvi-up branch doesn't yet have the http example working.  It's my next task when I get back to that part of the project.  I'm currently finishing a new package manager called lit.

Again, build using the master branch if you want the old behavior as documented on the luvit.io website.

In the new luvi-up branch, the `lib/luvit` code is unused and it's a current task to port it to the new `app/modules` folder for luvit 2.0.

**Comment by rmbishop** [comment]
OK thanks for the help.  Luvit.io website is down, BTW.

Ryam

**Comment by creationix** [comment]
This is fixed in the new README to luvit 2.0 and at new text luvit.io.
