### ISSUE TITLE
Add support for child_process stdio 'ipc' method

### ISSUE THREAD

**Issue by rphillips** [luvit/luvit#603]
This needs to include support for child.send events and process.on('message') events.

https://iojs.org/api/child_process.html#child_process_child_send_message_sendhandle

**Comment by joerg-krause** [comment]
Is there any news about this?

**Comment by creationix** [comment]
@joerg-krause It's a low priority issue, we're not working on it.  If you have a need for it, that can be changed or you can work on it.

**Comment by joerg-krause** [comment]
Thanks for invitation! I am novice to Lua programming trying to switch some projects from Node.js to luvit.

I am using named pipes for communication between parent and child process for now - so it is not urgent for me, too. But of course, it would be nice to have :smile:

**Comment by SinisterRectus** [comment]
I have a user that may benefit from this. I'll take a stab at it and see what I come up with. Although I prefer to use coro-spawn when possible, the benefit here is that you can integrate with the `process` module for IPC.

**Comment by SinisterRectus** [comment]
This turned out to be more difficult to implement than I thought it would be, so I'll put this aside. It's easier to build IPC on top of coro-spawn and coro-net than it is here.
