### ISSUE TITLE
Time in milliseconds

### ISSUE THREAD

**Issue by pablobcb** [luvit/luvit#651]
I am aware  that time in milliseconds is not possible in pure lua. Is there a way to fetch it in Luvit?

**Comment by imzyxwvu** [comment]
Have you tried os.clock()?

**Comment by creationix** [comment]
There are a few time related APIs in the luv bindings.  You can see them here in the libuv docs http://docs.libuv.org/en/v1.x/misc.html (that part of the luv docs aren't done yet https://github.com/luvit/luv/blob/master/docs.md#miscellaneous-utilities)
