### ISSUE TITLE
luvit.io is outdated

### ISSUE THREAD

**Issue by devurandom** [luvit/luvit#658]
https://luvit.io/ mentions the version number as 0.8.2, so people might assume the project is dead since years, while in reality lots of things happened since then.

**Comment by creationix** [comment]
Updating the site now, also porting over to actually run on luvit (currently it's hosted by node)

**Comment by devurandom** [comment]
See-Also: #397

**Comment by creationix** [comment]
Site is updated with correct information.  I don't have time to do a redesign though, any help here would be appreciated. https://luvit.io/
