### ISSUE TITLE
http ClientRequest should emit 'response'

### ISSUE THREAD

**Issue by tim-smart** [luvit/luvit#664]
https://github.com/luvit/luvit/blob/master/deps/http.lua#L301

I think this line might need changing?

**Comment by creationix** [comment]
I see, there are a few places here that should probably replace `:once` with `:emit`.  I'll double check with @rjemanuele.

**Comment by creationix** [comment]
@tim-smart this should help https://github.com/luvit/luvit/commit/0beb7f50bc1a6182ad8f0246ba858480daf8006f
