### ISSUE TITLE
http post appears to lose the first chunk of data

### ISSUE THREAD

**Issue by rphillips** [luvit/luvit#668]
I'm going through the keystone (identity client) and lose the data events for the response. I think this tests reproduces the issue.

https://gist.github.com/rphillips/384641f12b8580ff643f

**Comment by rphillips** [comment]
Looks like the data is there... perhaps the extra data needs to be processed?

https://github.com/luvit/luvit/blob/master/deps/http.lua#L166-L177

**Comment by joerg-krause** [comment]
Confirmed. No data received for POST methods.
