### ISSUE TITLE
Make modules in /deps standalone

### ISSUE THREAD

**Issue by LennyPenny** [luvit/luvit#685]
Would be awesome if you made the modules that aren't closely tied to luvi/luvit standalone lua modules to make using them with just luv super easy. 

Anyway great work!

**Comment by creationix** [comment]
They are already standalone lit modules?  There wan an outstanding issue to document the inter-dependencies between them so you cherry pick one and get it's deps.   That issue seems to have dissapeared though, hmm..

Which in particular do you have in mind?  Modules like http-codec are already used outside luvit, but within the luvi/lit ecosystem for example.

**Comment by LennyPenny** [comment]
Yeah things like http codec. Would be cool to officially have them for the lua world instead of the just the luvi/lit one. 

Right now I'm copying them from /deps and just putting local exports = {} at the top and return exports at the bottom and then fixing the paths of their required modules but that makes updating harder.

**Comment by creationix** [comment]
What exactly are you suggesting though?  Luvit's require system and normal lua are not compatible.  Also to be single-file lit packages, that also require anything, you have to assume a global "exports" and set exports.name and exports.version before calling require.

**Comment by Romaboy** [comment]
[fine example](https://github.com/luvit/luvit/blob/master/deps/http.lua) of very basic thing - http, which just fails with module 'luvi' not found. Module "luvi" not found not only locally, but also in luvit and luarocks module.
> What exactly are you suggesting though?
Maybe not every package in luvit will work fine with pure and great LuaJIT, but just look on this single line of code:
```lua
ClientRequest._defaultUserAgent = 'luvit/http luvi/' .. luvi.version
```
That's all! Only one useless line with missing everywhere dependency. I know, around 95% of lua amazing tools and libraries are forever in beta, but such things aren't serious at all.

**Comment by SinisterRectus** [comment]
Luvit modules are available via lit. For example, `lit install luvit/http-codec`. Closing this otherwise as stale. Please re-open if there is still an issue.

**Comment by squeek502** [comment]
Similar to / duplicate of https://github.com/luvit/luvit/issues/870
