### ISSUE TITLE
Is luvit has a stand module manager system like npm?

### ISSUE THREAD

**Issue by jackiesun8** [luvit/luvit#687]
The doc is not enough  to explain how to organize project structure.

**Comment by jackiesun8** [comment]
May be some examples is wonderful :)

**Comment by creationix** [comment]
The lit wiki pages have some up-to-date docs regarding organizing projects. 
https://github.com/luvit/lit/wiki

Also see the following example projects:

 - [lit](https://github.com/luvit/lit) - A luvi app that uses some of the main luvit libraries and mixes in coro-based libraries.
 - [rye](https://github.com/creationix/rye) - The start to a web publishing platform
 - [luvit.io](https://github.com/luvit/luvit.io) - A luvit app that uses coro code but runs with luvit.

And the following libraries:

 - [weblit](https://github.com/creationix/weblit) - The web framework used by luvit.io
 - [hoedown](https://github.com/creationix/lit-hoedown) - An FFI based binary library (markdown converter)
 - [glfw](https://github.com/creationix/lit-glfw) - Another FFI based binary library (cross-platform GUI toolkit)
 - [termbox](https://github.com/creationix/lit-termbox) - FFI based termbox library (terminal GUI toolkit)

**Comment by creationix** [comment]
We're still learning what the best practices are, share what workflows you discover that work well.
