### ISSUE TITLE
Luvi stops responding when msvc runtime not installed

### ISSUE THREAD

**Issue by bjconlan** [luvit/luvit#725]
when performing an install via `PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"`the installation stops with a windows `'luvi.exe' has stopped working` error.

When running the application via explorer a good ole 'msvcr_120.dll' error rears its head.

this can be solved by downloading the appropriate runtime via http://www.microsoft.com/en-US/download/details.aspx?id=40784 

This was only made obvious on a fresh windows install but it might be good to have it documented when installing via the prebuilt binaries/via powershell.

**Comment by creationix** [comment]
@rjemanuele I think that when we switched to including debug symbols it stopped building static binaries for windows.  The code is still at https://github.com/luvit/luvi/blob/master/CMakeLists.txt#L7-L20, but you'll notice the windows binaries are smaller than before we turned debug symbols on https://github.com/luvit/luvi/releases

**Comment by creationix** [comment]
We reverted back to using release builds of luvi.  As soon as the builds finish you can `lit update` to get the new luvi at v2.0.6.
If you want to patch yours directly, the windows build is already done at https://github.com/luvit/luvi/releases/tag/v2.0.6
