### ISSUE TITLE
Fail while trying make luvit 2.1.4 on windows

### ISSUE THREAD

**Issue by Playermet** [luvit/luvit#726]
Lit trying download "https://github.com/luvit/luvi/releases/download/v2.0.4/
luvi-regular-Windows_x86_64", which does not exist. After failing he prints whole content of github 404 page.

Luvit 2.1.3 making without problems.

**Comment by creationix** [comment]
What are you doing that's trying to download that url?

The get-list script has the correct pattern as does the on-demand luvi downloader in lit make 

- https://github.com/luvit/lit/blob/master/libs/core.lua#L45-L54
- https://github.com/luvit/lit/blob/master/get-lit.ps1#L5-L6

Perhaps you have an older version of lit before I fixed the path for windows? https://github.com/luvit/lit/commit/129c16fb7477e265aecfed65d5eb1900cc5f7c7f

If so, you'll need to manually reinstall lit using the get-lit script.

**Comment by squeek502** [comment]
Yeah, if you have lit < 1.1.7, you'll need to manually reinstall lit.

**Comment by creationix** [comment]
Closing issue. If manually installing lit 1.1.8 doesn't help, please reopen.
