### ISSUE TITLE
0.8.2 memory leak

### ISSUE THREAD

**Issue by yangzhu6263736** [luvit/luvit#734]
I have a project using 0.8.2 development，
![img_1520](https://cloud.githubusercontent.com/assets/1215298/7728855/1d78fec8-ff44-11e4-9fd0-5455e06c9415.JPG)
I met the memory leak,  Like this picture, collectgarbage("collect") said using the 9m memory, but the actual is 180m。
Upgrade can solve this problem？

**Comment by creationix** [comment]
It depends where the leak is.  If it's lua heap trapped by your code,
upgrading luvit won't have any effect.  If it's some leak in the luvit
bindings to libuv then perhaps it was fixed in the new version.  We have
lots of unit tests checking against leaks in the new luv bindings.

**Comment by SinisterRectus** [comment]
Closing as stale.
