### ISSUE TITLE
failed to start weblit on the win32 

### ISSUE THREAD

**Issue by runner-mei** [luvit/luvit#736]
[string "d:/developing/xxxxx/src/sampling/lua_bri..."]:25: bad argument #1to 'start' (Invalid Signal name)
stack traceback:
[C]: in function 'start'
[string "d:/developing/xxx/src/sampling/lua_bri..."]:25: in function 'fn'
[string "bundle:deps/require.lua"]:275: in function 'require'
[string "d:/developing/xxx/src/sampling/lua_bri..."]:1: in function 'fn'
[string "bundle:deps/require.lua"]:275: in function 'require'
[string "d:\developing\go\xxx\src\sampling\lua_bri..."]:2: in function 'fn'
[string "bundle:deps/require.lua"]:275: in function 'require'
[string "bundle:main.lua"]:115: in function 'main'
[string "bundle:init.lua"]:34: in function <[string "bundle:init.lua"]:32>
[C]: in function 'xpcall'
[string "bundle:init.lua"]:32: in function 'fn'
[string "bundle:deps/require.lua"]:275: in function <[string "bundle:deps/require.lua"]:240>

**Comment by runner-mei** [comment]
weblit-app.lua: 25 require('uv').new_signal():start("sigpipe")
sigpipe is unsupport on the win32

**Comment by creationix** [comment]
Maybe we should check for the sigpipe constant before ignoring the signal. https://github.com/luvit/luv/blob/master/src/constants.c#L200
