### ISSUE TITLE
please print more information while version is error

### ISSUE THREAD

**Issue by runner-mei** [luvit/luvit#737]
I write my package.lua with a error:
````lua
  dependencies = {
    "creationix/weblit@a0.3.1",   -- here
    "luvit/luvit@2.1.12",
    "luvit/tap@0.1.0",
  },
````
I run "lit make" and failed with:
````
fail: [string "bundle:deps/semver.lua"]:20: Not a semver
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/semver.lua"]:20: in function 'parse'
        [string "bundle:deps/semver.lua"]:29: in function 'normalize'
        [string "bundle:libs/core.lua"]:336: in function 'processDeps'
        [string "bundle:libs/core.lua"]:497: in function 'make'
        [string "bundle:commands/make.lua"]:10: in function 'fn'
        [string "bundle:deps/require.lua"]:275: in function 'require'
        [string "bundle:main.lua"]:32: in function <[string "bundle:main.lua"]:20>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:20: in function <[string "bundle:main.lua"]:13>
````

I hope print  "creationix/weblit@a0.3.1" in error message.

**Comment by runner-mei** [comment]
I write my package.lua with a error:

  dependencies = {
    "creationix/weblit@a0.3.1",   -- here
    "luvit/luvit@2.1.12",
    "luvit/tap@0.1.0",
  },

I run "lit make" and failed with:

fail: [string "bundle:deps/semver.lua"]:20: Not a semver
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/semver.lua"]:20: in function 'parse'
        [string "bundle:deps/semver.lua"]:29: in function 'normalize'
        [string "bundle:libs/core.lua"]:336: in function 'processDeps'
        [string "bundle:libs/core.lua"]:497: in function 'make'
        [string "bundle:commands/make.lua"]:10: in function 'fn'
        [string "bundle:deps/require.lua"]:275: in function 'require'
        [string "bundle:main.lua"]:32: in function <[string "bundle:main.lua"]:20>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:20: in function <[string "bundle:main.lua"]:13>

I hope print "creationix/weblit@a0.3.1" in error message.

**Comment by creationix** [comment]
Thanks for taking time to report this.  Sorry for the trouble.  The fix will be in the next lit update.
