### ISSUE TITLE
feature request about http client

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvit#741]
Please consider to support Keep-alive HTTP header, and give a way to reuse HttpRequest object and socket.

**Comment by creationix** [comment]
I thought we did support http keep-alive.  I'm pretty sure the coro-http library used in lit does at least.  Perhaps it wasn't ported over for the node style library in the luvit metapackage?

**Comment by rphillips** [comment]
I believe we do support keep alive. there is a test here: https://github.com/luvit/luvit/blob/a502bca2daeb427c51dfde2bbc4dc0678d2909b8/tests/test-http-decoder.lua#L130

**Comment by zhaozg** [comment]
Sure http decoder support keep alive, but hot to apply to HttpRequest?
Please show me example.
```lua
local http = require('http')

local options = {
  host = '192.168.0.69',        -- proxy ip
  port = '80',                 -- proxy port
  path = '/1k.txt',
  headers = { {'connection','Keep-alive'}} --keep alive
}

local function HttpBeanch(uri, onResponse)
    return http.request(uri, onResponse)
end

local function reset(c)
    c.headers_sent = nil
end

local i =0
local c
local function onResponse(res)
    print(string.rep('-',78))
        local chunks = {}
        res:on('data', function (chunk)
            chunks[#chunks+1] = chunk
            i=i+1
        end)
        res:on('end', function()
            local body = table.concat(chunks)
            --print('Done',i,#body)
--            c.headers_sent = nil
--            c[4] = nil
            reset(c)
            p(c)
            c:done()  --try to do request again.
        end)
end

c = HttpBeanch(options,onResponse)
c:on('error',function(...) print(...) end)
p(c)
c:done() --do real request

```

**Comment by zhaozg** [comment]
According to https://github.com/luvit/luvit/blob/master/tests/test-http.lua,
I need use socket to send and parse http protocol, thanks.
