### ISSUE TITLE
dns resolver for `localhost` failed

### ISSUE THREAD

**Issue by lduboeuf** [luvit/luvit#742]
exports.name = "luvit/dns"
exports.version = "1.0.0-3"
https://github.com/luvit/luvit/blob/master/deps/dns.lua#L686
    dns.resolve4('localhost', expect(function(err, answers)... -> address is not resolved: { errcode = 3, errstr = 'name error' }

**Comment by creationix** [comment]
What OS is this?

**Comment by lduboeuf** [comment]
Linux x64

**Comment by rphillips** [comment]
you will want to call dns.loadResolver() in your app. We don't call it by default (yet) and default to google dns servers.

**Comment by creationix** [comment]
@rphillips, this is default behavior now right?

**Comment by rphillips** [comment]
we read the resolv.conf for the dns servers now on unix systems. We are not reading the hosts file yet, which is usually where the localhost entries are.

**Comment by creationix** [comment]
I think the solution is to use libuv's native dns functions when a user is just resolving a host to ip (like in the net module).  This supports `/etc/hosts` on all platforms I tested.

**Comment by creationix** [comment]
@lduboeuf what were you doing when you ran into this issue?  I'm assuming you were just making a normal TCP connection and wanted to resolve some hostname to get the IP?

**Comment by creationix** [comment]
Ok, the net module already uses `uv.getaddrinfo`.  @lduboeuf if you want to manually resolve something and wan to take into account system configuration, use `uv.getaddrinfo` instead of luvit's dns module which implements the dns protocol by hand using udp primitives.

**Comment by lduboeuf** [comment]
@creationix  if i remember. It was just to trying to connect to a local irc server by using 'localhost' not IP, i thought it might worked like this.  thanks for the feedback.
