### ISSUE TITLE
Listener on process:exit() is not called

### ISSUE THREAD

**Issue by gsick** [luvit/luvit#752]
Hi all,

Actions at `process:exit()` cannot run.
```lua
process:on("exit", function()
  --[[
  Cannot register listener on exit event.
  Only listener on error event or std system signals are allowed. (process.lua:87)
  Error: bad argument #2 to 'signal_start' (Invalid Signal name)
]]
end)

-- or

require("hooks"):on("process.exit", function()
  --[[
  Only called in normal termination otherwise is
  never called because process:exit() doesn't fire "process.exit" event through the "hooks"
  but "exit" event is fired ;) (process.lua:110)
]]
end)
```

There are at least two ways to fix the issue and I don't know which one is the best for you.

Thanks,

**Comment by creationix** [comment]
I think we want support for the old process:on("exit", ...) functionality.  I think it's just missing as an oversight.  The new test framework uses nested `uv.run()` instead of exit events to check for things at cleanup.

**Comment by gsick** [comment]
This is a really useful feature. It allows proper cleaning resources used by external libraries/deps who are not manage by the libuv loop  (like db connection, ...) or make some processing (like delete pid file, ..). If this is an oversight I'll send a PR.
