### ISSUE TITLE
HTTP client is too sensitive

### ISSUE THREAD

**Issue by creationix** [luvit/luvit#773]
The http client seems to only accept headers as nested tables (as opposed to keyed maps).  Also it doesn't switch to chunked encoding when there is no Content-Length included.

**Comment by creationix** [comment]
I like the low level design actually, but it's quite different from the node.js API and is confusing people.

**Comment by squeek502** [comment]
:+1: to the headers table format being confusing.

**Comment by creationix** [comment]
Related to luvit/luvit.io#9

**Comment by creationix** [comment]
Also see thread in mailing list titled "Http server code listed on luvit.io home page does not work."

**Comment by creationix** [comment]
After some testing, it seems this is mostly implemented as I thought.  There are reports it was working in full a few versions back.  The only case that I can find that doesn't work is when you use `res:writeHead(code, headers)` and don't specify a `Content-Length`, it won't auto-add the `Transfer-Encoding: Chunked`.
