### ISSUE TITLE
Submit luvit / lit / luvi to homebrew

### ISSUE THREAD

**Issue by creationix** [luvit/luvit#787]
This is almost done, but there are a few issues blocking us.

Depends on https://github.com/luvit/luvi/issues/113 and https://github.com/luvit/lit/issues/109

A start to the formulae is at https://gist.github.com/tzudot/dd956165cca423d57d71

**Comment by kaustavha** [comment]
+1 for hopefully making installation easier

**Comment by creationix** [comment]
Once done, report to https://github.com/Homebrew/homebrew/pull/42019

**Comment by creationix** [comment]
We're now unblocked on this.  Just need to test the new changes a bit, deploy the new lit to production and make a new luvi release.

**Comment by creationix** [comment]
@tzudot, I fixed the issues in luvi and lit.  Can you try to get it working with brew again?  Make sure to use at least:

```
lit: 2.2.4
luvit: 2.4.1
luvi: v2.1.8
```

I'll make an attempt tomorrow if you don't get to it.

**Comment by tzudot** [comment]
Where can I get the updated tarballs with submodules included? The previous release tarball link is not available anymore.
e.g. https://gist.github.com/tzudot/dd956165cca423d57d71#file-luvi-rb-L4

**Comment by creationix** [comment]
The latest luvi releases are always found at https://github.com/luvit/luvi/releases/latest.

This particular release is at https://github.com/luvit/luvi/releases/download/v2.1.8/luvi-src-v2.1.8.tar.gz.

The lit zip file is at the same url scheme with the latest being at https://lit.luvit.io/packages/luvit/lit/v2.2.4.zip

**Comment by creationix** [comment]
- The luvi url now has the version in the filename.
 - Luvi now creates zips with proper CRC32 checksums and so the zips on lit.luvit.io have correct CRCs
 - Packages are snapshotted when published with a frozen set of dependencies, this is used to generate the zip files at lit.luvit.io.

**Comment by tzudot** [comment]
Thank you for pointing me to those URLs, again. The `luvi` installation went fine but there is an issue with `lit`, https://gist.github.com/tzudot/b79c4baa67bfb2fac371. I have tried `lit` installation manually, as well, using the Homebrew formula but it failed. Could you check this error.

**Comment by creationix** [comment]
@tzudot, ok, I fixed the luvi build to include a proper version when built from tarball. https://github.com/luvit/luvi/commit/e59881b0020ca0c228dc1c3447f68a06ee4b7def

I've updated the existing tarball so it should work now if you try again.  You'll need to update the SHA256 for the luvi tarball.

**Comment by creationix** [comment]
I went ahead and tried to finish this myself as can be seen in the homebrew PR above.  It does seem to work fine, but I'm unsure if we should stick to the official luvit build (static dependencies) or the homebrew style (shared dependencies).  Luvi can be built either way.

**Comment by tzudot** [comment]
Cool 👍🏽, `Homebrew` now has a working `luvit` formula from the core team. I'll try out building/using `luvit` ( and depending packages too? ) using `Homebrew` dependencies, and look out for any  repercussions of this process.

**Comment by creationix** [comment]
I do know of at least one issue with the homebrew version.  Possible solutions are discussed at https://github.com/luvit/lit/issues/115
