### ISSUE TITLE
luvit executable vs luvit bundle performance

### ISSUE THREAD

**Issue by jcmoore** [luvit/luvit#789]
I'm interested in running luvit in docker containers based from alpine linux (due to it's small image size/footprint -- https://github.com/gliderlabs/docker-alpine).

The images I've built (see https://gist.github.com/jcmoore/4a8eb89a98b7d95b5b83#file-readme-sh-L2 if maybe you're interested in officially supporting alpine) only include the luvi regular executable and the .zip bundles for luvit and lit.  I'm planning to run luvit like so -- https://gist.github.com/jcmoore/4a8eb89a98b7d95b5b83#file-luvit-sh-L2 -- but I'm wondering what the performance implications are of running it this way instead of through an executable (from `lit make`).  Is the performance going to be impacted during the life of process or does compiling with lit just make luvit load faster initially?

**Comment by creationix** [comment]
Luvi has the ability to use a shared luvi binary in the form of unix shebang lines.  I designed this feature just for places where space is minimal or you just don't like duplicating the luvi binary everywhere.

Start out a file with one line:

```sh
#!/usr/local/bin/luvi --
```

And then append the binary zip to it.  And mark it as executable.

There is a special rule in luvi's command line parsing where if `--` is found and no path to the luvi app was found, it will assume the next argument is the path to zip or directory.  Then the rest of the args will be passed through to the app as-is.

As far as performance, this will work the same as if luvi and the zip were in the same file.  Luvi opens and reads the zip file using normal filesystem APIs, it doesn't matter where the zip is.  The other special logic is the luvi binary will check itself to see if there is a bundled zip appended and use the path to it's self for the app path.

**Comment by creationix** [comment]
Regarding your technique using `sh`.  That should perform the same once running.  You do have the extra overhead of running `/bin/sh` and leaving it running.  If you wanted to, you could still keep the zip file separate without including sh.

I would recommend adding the shebang line to the top of your zip files, mark them as executable, and use them directly (or via symlink).

**Comment by jcmoore** [comment]
Thanks, I've updated my build scripts (revising my gists) according to your recommendations.

**Comment by creationix** [comment]
I noticed you're pulling in openssl and libgcc when using luvi.  The default build should comes with openssl statically linked and does not need the system version (unless you're making a custom build).

**Comment by jcmoore** [comment]
So I might be able to get rid of the openssl dependency if I pull the .zip fetching out of the lituvit.dockerfile itself (see https://gist.github.com/jcmoore/4a8eb89a98b7d95b5b83#file-lituvit-dockerfile-L9-L10), but when I try to run luvit/lit/luvi in the container, I get:

```
/ # luvit
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/luvit)
Error relocating /usr/local/bin/luvit: _Unwind_RaiseException: symbol not found
Error relocating /usr/local/bin/luvit: _Unwind_GetCFA: symbol not found
Error relocating /usr/local/bin/luvit: _Unwind_SetGR: symbol not found
Error relocating /usr/local/bin/luvit: _Unwind_DeleteException: symbol not found
Error relocating /usr/local/bin/luvit: _Unwind_SetIP: symbol not found
/ # lit
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/lit)
Error relocating /usr/local/bin/lit: _Unwind_RaiseException: symbol not found
Error relocating /usr/local/bin/lit: _Unwind_GetCFA: symbol not found
Error relocating /usr/local/bin/lit: _Unwind_SetGR: symbol not found
Error relocating /usr/local/bin/lit: _Unwind_DeleteException: symbol not found
Error relocating /usr/local/bin/lit: _Unwind_SetIP: symbol not found
/ # luvi
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /usr/local/bin/luvi)
Error relocating /usr/local/bin/luvi: _Unwind_RaiseException: symbol not found
Error relocating /usr/local/bin/luvi: _Unwind_GetCFA: symbol not found
Error relocating /usr/local/bin/luvi: _Unwind_SetGR: symbol not found
Error relocating /usr/local/bin/luvi: _Unwind_DeleteException: symbol not found
Error relocating /usr/local/bin/luvi: _Unwind_SetIP: symbol not found
```

unless I pull in libgcc.

**Comment by creationix** [comment]
Sounds like you have a pretty minimal system indeed.  I'm pretty sure you'll need libgcc if you build luvi using gcc, but if I understand right, you should **not* also need openssl libs.

**Comment by creationix** [comment]
Of course, since you're building luvi from source, you should probably just tell the luvi build to use the system openssl.  I'm sure other things on your system will need it and there is no reason for luvi to have it's own copy.  Openssl is huge!

**Comment by jcmoore** [comment]
Hmmm, so if what you mean is building luvi with `make tiny && make` with openssl installed at a system level, I had tried that, but when I try to use the executable later (like `./luvi lit.zip -- install gsick/uuid`) I get the following error:

```
lit version: 2.1.11
luvi version: v2.1.7-1-g0896921
command: install gsick/uuid
fail: [string "bundle:deps/require.lua"]:269: No such module 'openssl' in 'bundle:/deps/coro-tls.lua'
module 'openssl' not found:
	no field package.preload['openssl']
	no file './openssl.lua'
	no file '/usr/local/share/luajit-2.0.4/openssl.lua'
	no file '/usr/local/share/lua/5.1/openssl.lua'
	no file '/usr/local/share/lua/5.1/openssl/init.lua'
	no file './openssl.so'
	no file '/usr/local/lib/lua/5.1/openssl.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
stack traceback:
	[C]: in function 'error'
	[string "bundle:deps/require.lua"]:269: in function 'require'
	[string "bundle:/deps/coro-tls.lua"]:9: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/deps/coro-http.lua"]:19: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/libs/github-request.lua"]:22: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/libs/core.lua"]:33: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/commands/install.lua"]:2: in function 'fn'
	[string "bundle:deps/require.lua"]:291: in function 'require'
	[string "bundle:/main.lua"]:50: in function <[string "bundle:/main.lua"]:38>
	[C]: in function 'xpcall'
	[string "bundle:/main.lua"]:38: in function <[string "bundle:/main.lua"]:31>
```

Maybe there is something weird about where alpine puts the lib -- or is it that I'm actually just missing lua dependencies that can be fulfilled another way?

**Comment by creationix** [comment]
No, `make tiny` doesn't include openssl at all.  You'll have to pass in the Cmake options directly instead of using the makefile.
https://github.com/luvit/luvi/blob/master/Makefile#L67
https://github.com/luvit/luvi/blob/master/CMakeLists.txt#L40-L55

**Comment by jcmoore** [comment]
Thanks, updated the build process and saved nearly 3MB on the final image (now < 8.8MB total) when using system openssl (strangely though, using a system pcre makes the overall image bigger -- by 200k -- rather than smaller)
