### ISSUE TITLE
cannot connect to luvit in docker container through exposed ports

### ISSUE THREAD

**Issue by jcmoore** [luvit/luvit#791]
Tested with both Ubuntu 14.04 and boot2docker as host OS
Tested with both Ubuntu 14.04 and alpine as container OS
Tested with the canonical hello world server example:

```
local http = require('http')

http.createServer(function (req, res)
  local body = "Hello world\n"
  res:setHeader("Content-Type", "text/plain")
  res:setHeader("Content-Length", #body)
  res:finish(body)
end):listen(1337, '127.0.0.1')
```

Tested in a container exposing port 1337 in the host -- a la `docker run --rm -it -p 1337:1337 ubuntu` (and manually installing luvit inside)

localhost:1337 CAN be reached from the container OS
localhost:1337 CANNOT be reached from the host OS
curl returns `curl: (52) Empty reply from server`
wget returns `wget: error getting response: Connection reset by peer`

Though it would seem likely that this is an issue with docker itself, comparable node.js hello-world servers could be properly reached from the host OS in all previously mentioned combinations of host/container OS's (that's why I'm bringing the issue here)

**Comment by creationix** [comment]
Can you try binding to port `0.0.0.0` instead of `127.0.0.1` if you want the service available outside itself.  It shouldn't matter with port forwards since those come from the inside, but maybe docker does something weird.

**Comment by jcmoore** [comment]
Awesome, binding to 0.0.0.0 in the canonical example seems to work just fine.  Glad there was a very simple way around this.  Thanks.
