### ISSUE TITLE
Luvit childprocess breaks on red hat

### ISSUE THREAD

**Issue by kaustavha** [luvit/luvit#797]
When attempting to use childprocess.spawn with a command that lives somewhere else on red hat than debian it fails, often resulting in an exit code of 127. 
E.g on rhel
```sh
which lsof
/usr/sbin/lsof
```
On ubuntu
```sh
/usr/bin/lsof
```
A script using spawn with lsof will work fine on ubuntu but break on rhel. 
You can run any of the hostinfo checks in the virgo-agent-toolkit/rackspace-monitoring-agent to confirm this, look for checks that use the execfiletobuffers or asyncspawn misc function.

**Comment by creationix** [comment]
Spawn requires the path to the command and it's arguments explicitly.  If you want to run a shell command, you need to run it through sh.

Node's exec wrapper does this by using `"/bin/sh"` with `{"-c", command}` as args. (on windows it uses cmd.exe with it's flags)

**Comment by rphillips** [comment]
Or pass { env = process.env } to the spawn function within the options.

**Comment by kaustavha** [comment]
Fixed with a 
```lua
if not options.env then options.env = process.env end
```
