### ISSUE TITLE
lit/luvit package community requests

### ISSUE THREAD

**Issue by james2doyle** [luvit/luvit#810]
I think that in order to grow the popularity of luvit "in the wild", it would be cool to have an area (repo, forum, wiki, etc) where people could request packages to be made. Possibly, even request packages be migrated from node/iojs.

A portion of [my packages](https://github.com/search?q=user%3Ajames2doyle+lit) have been migrated directly from node packages.

I think it could be a good initiative. It could also show people how easy (relatively speaking) it is to migrate JS to Lua.

Any thoughts?

**Comment by creationix** [comment]
Sounds great.  You should be able to make a wiki page and then send an email to the mailing list to tell people about it.

Though a github issue may work better since that will show up in the feeds of everyone who watches luvit and is better for discussions.  Whichever you think will work better.

**Comment by james2doyle** [comment]
Ok sure I can do that
