### ISSUE TITLE
Memory leak in examples/http-server.lua

### ISSUE THREAD

**Issue by miko** [luvit/luvit#821]
Hello,
There is a memory leak when stress-testing examples/http-server.lua:

```
luvit examples/http-server.lua 
Server listening at http://localhost:8080/
```
with ab:
```
ab -n 100000 -c 200 http://127.0.0.1:8080/
```
with a result:
```
Uncaught Error: not enough memory
```
My env:
```
luvit --version
luvit version: 2.5.3
luvi version: v2.3.3
rex version: 8.37 2015-04-28
libuv version: 1.7.3
ssl version: OpenSSL 1.0.2d 9 Jul 2015, lua-openssl 0.4.1
```
Running on archlinux. Memory consumption grows with each new request. Running collectgarbage() periodically does not help.
Looking for confirmation and (better yet) a solution.

**Comment by creationix** [comment]
Thanks for the report, I'll look into this.

**Comment by creationix** [comment]
Found the leak!  It's https://github.com/luvit/luvit/blob/master/deps/http.lua#L337 leaking it's handler and closure.  Now to see how to fix this.

**Comment by miko** [comment]
After looking at the code it seems to me that Emitter:unonce() would be needed... I think it affects all the cases where a callback registered with once() is no longer needed.

**Comment by creationix** [comment]
I thought we had fixed the leak with once.  I don't want to make an `unonce`, it should just do the right thing.  I can double check the once code.

But after looking closer it is still leaking after my patch, just much slower (about 600 bytes per htttp request).

**Comment by creationix** [comment]
If you use the latest luvi with the new `snapshot` tool, you can see the actual heap objects that are new since last snapshot as well as objects that didn't go away between snapshots (likely leaks).

```lua
local http = require("http")
local https = require("https")
local pathJoin = require('luvi').path.join
local fs = require('fs')
local timer = require('timer')

local snapshot = require('snapshot')

local S1, C1

local i = 0

local function onRequest(req, res)
  --print(req.socket.options and "https" or "http", req.method, req.url)
  local body = "Hello world\n"
  res:setHeader("Content-Type", "text/plain")
  res:setHeader("Content-Length", #body)
  res:finish(body)

  collectgarbage()
  timer.setTimeout(100, function ()
    collectgarbage()
    local C2 = collectgarbage("count")
    local S2 = snapshot()
    local c = 0
    for k,v in pairs(S2) do
    	if S1[k] == nil then
        c = c + 1
    		-- p(k)
        -- print(v)
    	end
    end
    print(C2, C2-C1, c)
    S1 = S2
    C1 = C2
    i = i + 1
  end)


end

http.createServer(onRequest):listen(8080)
print("Server listening at http://localhost:8080/")

https.createServer({
  key = fs.readFileSync(pathJoin(module.dir, "key.pem")),
  cert = fs.readFileSync(pathJoin(module.dir, "cert.pem")),
}, onRequest):listen(8443)
print("Server listening at https://localhost:8443/")

collectgarbage()
S1 = snapshot()
C1 = collectgarbage("count")
```

I still need to filter out objects that went away after one cycle.

**Comment by creationix** [comment]
I refactored the code into a standalone leak-check tool.

```lua
local snapshot = require('snapshot')
local potential = {}
local S1
local function leakCheck()
  -- Take a heap measurement and snapshot
  collectgarbage()
  local C2 = collectgarbage("count")
  local S2 = snapshot()

  -- If we have history, do some analysis
  if S1 then
    local count = 0

    -- Log and objects that were in the old potential list and are still around.
    -- Also clear the potential list
    for i = #potential, 1, -1 do
      local k = potential[i]
      local v = S2[k]
      if v then
        count = count + 1
        p(k)
        print(v)
      end
      potential[i] = nil
    end

    -- Store the keys for all heap objects that are new since last snapshot.
    for k, v in pairs(S2) do
      if S1[k] == nil then
        potential[#potential + 1] = k
      end
    end

    -- Log some heap statistics
    print("Heap: " .. C2 .. "kb, Leaked Objects: " .. count)

  end

  -- What was new is now old.
  S1 = S2
end
```

Call this in your request loop.  The first call won't output anything since it's gathering history, but all calls after that will show leaking objects as well

**Comment by creationix** [comment]
Using the tool, I can see I'm leaking 48 objects without the exit-once patch and zero objects afterwards.  Whatever is causing that remaining 600-700 bytes of leak is not lua objects on the heap.

**Comment by creationix** [comment]
It seems the leak is gone, the heap growing slowly must be the tracing jit warming up or something.  It flat-lines after a while.
