### ISSUE TITLE
timer:active() - attempt to call method 'active' (a nil value)

### ISSUE THREAD

**Issue by ghost** [luvit/luvit#838]
The [Luvit docs describe](https://luvit.io/api/timer.html) a `timer:active()` method, which does not actually exist (`attempt to call method 'active' (a nil value)`). The [NodeJS docs](https://nodejs.org/api/timers.html) don't describe that function at all.

What I actually want is to see whether a timer was `close()`d. Thus I stumbled over the `active()` method in the docs.

**Comment by creationix** [comment]
@kaustavha do you know where `timer:active()` came from in the docs?

**Comment by kaustavha** [comment]
@urzds @creationix 
https://github.com/luvit/luvit/blob/master/deps/timer.lua#L258-L270
```
local timer = require('timer')
> timer.active
function: 0x0d7754b0
> timer:active() -- This doesnt exist
> timer.active()
[string "bundle:deps/timer.lua"]:260: attempt to index local 'item' (a nil value)
stack traceback:
	[string "bundle:deps/timer.lua"]:260: in function <[string "bundle:deps/timer.lua"]:259>
	[C]: in function 'xpcall'
	[string "bundle:deps/repl.lua"]:93: in function 'evaluateLine'
	[string "bundle:deps/repl.lua"]:177: in function <[string "bundle:deps/repl.lua"]:175>
```

**Comment by rphillips** [comment]
timer.active requires an object to be passed to it.
