### ISSUE TITLE
setTimeout vararg with nil argument

### ISSUE THREAD

**Issue by bjornbytes** [luvit/luvit#841]
Running the following in the REPL:

``` lua
timer.setTimeout(0, print, 1, nil, 3)
```

only prints '1', even though `setTimeout` should pass the last three arguments to `print`.

In `deps/timer.lua#setTimeout`, I tried changing the `local args = {...}` line to:

``` lua
  local args = {n = select('#', ...), ...}
```

But this didn't seem to help.  The following fixed it though:

``` lua
  local args = table.pack(...)
```

I would have thought that using `select` would have fixed things, but it appears to be a strange issue specific to LuaJIT.  Using `table.pack` is a feature in the `LUA52_COMPAT` extension -- I'm not sure if that's safe to use here.  If so, I can open up a PR.

**Comment by creationix** [comment]
Luvit assumes luajit 5.2 compat features are turned on since it's based on luvi which sets the flag in the official binaries.

**Comment by creationix** [comment]
Also, I can confirm the behavior you're seeing.  I'm not sure what the difference it.

```lua
> a = table.pack(nil, nil, 3)
> b = {n=3,[3]=3}
> b
{ [3] = 3, n = 3 }
> a
{ [3] = 3, n = 3 }
> #a
3
> #b
0
```

**Comment by SinisterRectus** [comment]
Resurrecting this. Seems that there are 4 different conditions that can be reached in different ways:

- A = has n, len = n
- B = has n, len = 0
- C = no n, len = n
- D = no n, len = 0

Input:
```lua
local tests = {
    table.pack(nil, nil, 3), -- A
    {n = 3, nil, nil, 3}, -- A
    (function(...) return table.pack(...) end)(nil, nil, 3), -- A
    {n = 3, [3] = 3}, -- B
    (function(...) return {n = select('#', ...), ...} end)(nil, nil, 3), -- B
    {nil, nil, 3}, -- C
    (function(...) return {...} end)(nil, nil, 3), -- D
}

for i, v in ipairs(tests) do
    p(i, #v, v)
end
```

Output:
```lua
1       3       { [3] = 3, n = 3 }
2       3       { [3] = 3, n = 3 }
3       3       { [3] = 3, n = 3 }
4       0       { [3] = 3, n = 3 }
5       0       { [3] = 3, n = 3 }
6       3       { [3] = 3 }
7       0       { [3] = 3 }
```

**Comment by SinisterRectus** [comment]
The behavior is unpredictable, but consistent across PUC Lua. It looks like LuaJIT is doing something different when packing `{...}`.

| input                                                               | 5.1 # / n | 5.2 # / n | 5.3 # / n | luajit # / n |
|---------------------------------------------------------------------|-----------|-----------|-----------|--------------|
| {nil, nil, 3}                                                       | 3 / nil   | 3 / nil   | 3 / nil   | 3 / nil      |
| {n = 3, [3] = 3}                                                    | 0 / 3     | 0 / 3     | 0 / 3     | 0 / 3        |
| {n = 3, nil, nil, 3}                                                | 3 / 3     | 3 / 3     | 3 / 3     | 3 / 3        |
| (function(...) return {n = select('#', ...), ...} end)(nil, nil, 3) | 3 / 3     | 3 / 3     | 3 / 3     | 0 / 3        |
| (function(...) return {...} end)(nil, nil, 3)                       | 3 / nil   | 3 / nil   | 3 / nil   | 0 / nil      |
| (function(...) return table.pack(...) end)(nil, nil, 3)             | n/a       | 3 / 3     | 3 / 3     | 3 / 3        |
| table.pack(nil, nil, 3)                                             | n/a       | 3 / 3     | 3 / 3     | 3 / 3        |

**Comment by creationix** [comment]
fun times :/
