### ISSUE TITLE
How to use Luvit with LuaCov or LuaTrace?

### ISSUE THREAD

**Issue by urzds** [luvit/luvit#843]
I am trying to make a coverage analysis of my tests using [LuaCov](http://keplerproject.github.io/luacov/). However, the coverage stats only include measures of `luvipath.lua` and `luvibundle.lua`, but completely miss anything else.

Example with `testthis.lua`:
```lua
function testthis()
        print("testthis")
end

testthis()
```

```
# luvit -e 'jit.off(); jit.flush(); local luacov = require("luacov");' testthis.lua
testthis
# cat luacov.stats.out
107:/home/tim/luvi/src/lua/luvipath.lua
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 11 0 0 11 31 20 0 11 0 0 5 2 0 3 0 0 0 0 5 5 0 0 0 5 5 11 22 11 6 0 0 0 5 4 0 0 0 5 16 11 31 20 0 11 0 0 0 5 5 25 20 20 20 1 19 1 0 18 0 0 0 0 0 5 13 8 8 0 0 5 5
```

I compared this with plain LuaJIT:
```
# rm luacov.stats.out
# luajit -e 'jit.off(); jit.flush(); local luacov = require("luacov");' testthis.lua
testthis
# cat luacov.stats.out
5:testthis.lua
1 1 2 0 2
```

At first I assumed that all of this is caused by LuaJIT, as [described for LuaTrace](https://github.com/geoffleyland/luatrace/blob/master/README.md):
> luatrace runs under "plain" Lua and LuaJIT with the -joff option (LuaJIT doesn't call hooks in compiled code, and luatrace loses track of where it's up to)

However, even with the JIT enabled, plain LuaJIT still creates the desired output in my very simple test-case:
```
# rm luacov.stats.out
# luajit -e 'jit.on(); local luacov = require("luacov");' testthis.lua
testthis
# cat luacov.stats.out
5:testthis.lua
1 1 2 0 2 
```

So it is unclear what happens, but somehow Luvit prevents LuaCov from seeing the interpreter progress.

The same behaviour can be observed for [LuaTrace](https://github.com/geoffleyland/luatrace).

```
# luvit -e 'jit.off(); jit.flush(); local luatrace = require("luatrace"); luatrace.tron();' tests/run.lua
```

So apparently they both use the same path, which is blocked by Luvit.

**Comment by urzds** [comment]
Example with `testthis.lua`:
```lua
function a()
        print("a")
end

a()
```

```
# luajit -e 'jit.off(); jit.flush(); local luacov = require("luacov");' testthis.lua
a
# cat luacov.stats.out
5:testthis.lua
1 1 2 0 2 
# rm luacov.stats.out
# luvit -e 'jit.off(); jit.flush(); local luacov = require("luacov");' testthis.lua
a
# cat luacov.stats.out
107:/home/tim/luvi/src/lua/luvipath.lua
0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 11 0 0 11 31 20 0 11 0 0 5 2 0 3 0 0 0 0 5 5 0 0 0 5 5 11 22 11 6 0 0 0 5 4 0 0 0 5 16 11 31 20 0 11 0 0 0 5 5 25 20 20 20 1 19 1 0 18 0 0 0 0 0 5 13 8 8 0 0 5 5 
```

**Comment by urzds** [comment]
Looking at [`luacov.runner.init()`](https://github.com/keplerproject/luacov/blob/60fe27fd461eb4cef583669b10ebf599e79c3849/src/luacov/runner.lua#L383), it seems that LuaCov needs to be notified of the creation of all coroutines, because it has to enable tracing individually for all of them.

This is probably the reason why enabling luacov or luatrace from `luvit -e ...` has no (significant) effect: The coroutines where the real action happens are created elsewhere.

Figuring out where prevented my further advancement so far: It appears as if there is no related call to `coroutine.create()` in the whole of Luv/i/t and `lua_newthread()` is not called anywhere at all...

**Comment by urzds** [comment]
On IRC I got the hint that `utils.adapt()` supposedly wraps all callbacks.

I tried to hook into that with following patches:
```diff
diff --git a/deps/utils.lua b/deps/utils.lua
index 40990ee..67436b8 100644
--- a/deps/utils.lua
+++ b/deps/utils.lua
@@ -72,6 +72,8 @@ local function adapt(c, fn, ...)
   local t = type(c)
   if t == 'function' then
     args[nargs + 1] = c
+    print("LUVIT: ON:ADAPT(FUNCTION)")
+    _onadapt(c)
     return fn(unpack(args))
   elseif t ~= 'thread' then
     error("Illegal continuation type " .. t)
@@ -89,6 +91,8 @@ local function adapt(c, fn, ...)
       c = nil
     end
   end
+  print("LUVIT: ON:ADAPT(THREAD)")
+  _onadapt(c)
   fn(unpack(args))
   if c then
     waiting = true
@@ -100,6 +104,14 @@ local function adapt(c, fn, ...)
   end
 end
 
+local _onadapt = function() end
+
+local function onadapt(c)
+       print("LUVIT: SETTING ON:ADAPT")
+       _onadapt = c
+end
+
 exports.bind = bind
 exports.noop = noop
 exports.adapt = adapt
+exports.onadapt = onadapt
```
```diff
diff --git a/src/luacov/runner.lua b/src/luacov/runner.lua
index 8a8b768..b9adc5c 100644
--- a/src/luacov/runner.lua
+++ b/src/luacov/runner.lua
@@ -396,6 +396,27 @@ function runner.init(configuration)
 
    debug.sethook(on_line, "l")
 
+   print("LUACOV: INITIALISING")
+
+   local luvit_require = require("require")
+   if luvit_require then
+
+   local luvit_utils = luvit_require("")("utils")
+   if luvit_utils then
+     local onadapt = luvit_utils.onadapt
+     if onadapt then
+       print("LUACOV: WILL SET ONADAPT")
+       onadapt(function(c)
+         print("LUACOV: ONADAPT CALLED")
+         if type(c) == "thread" then
+          print("LUACOV: ... WITH THREAD")
+          debug.sethook(on_line, "l")
+         end
+       end)
+     end
+   end
+   end
+
    -- debug must be set for each coroutine separately
    -- hence wrap coroutine function to set the hook there
    -- as well
```

However, my hook is never called:
```
# luvit -e 'jit.off(); jit.flush(); require("luacov");' testthis.lua
LUACOV: INITIALISING
LUACOV: WILL SET ONADAPT
LUVIT: SETTING ON:ADAPT
a
```

**Comment by creationix** [comment]
You also need to look for `coroutine.wrap` which is another way to create coroutines.

**Comment by urzds** [comment]
It was pointed out on IRC, in an [old mailinglist post](http://lua-users.org/lists/lua-l/2011-06/msg00513.html) and can be read on the [LuaJIT website](http://luajit.org/status.html), LuaJIT does not support per-coroutine debug hooks. So this should not be the reason for LuaCov not working with Luvit.

**Comment by urzds** [comment]
@mpeterv answered this in keplerproject/luacov#39:
> It seems that unlike Lua and LuaJIT Luvit does not prepend '@' to filenames when setting chunk name for a loaded file. Setting codefromstrings option to true in .luacov config should work. E.g.
> 
> ```lua
return {
   codefromstrings = true,
   include = {"testthis$"}
}
```

I'll submit a PR for the Readme in a bit.

**Comment by Miigon** [comment]
@urzds The `require()` of luvit was implemented by `loadstring()`,this may be the ploblem?

**Comment by urzds** [comment]
@Miigon Yes, that is basically the issue - see the quote above. The trick is to set `codefromstrings = true` in the `.luacov` configuration file.

I submitted the promised pull request as #922.

**Comment by urzds** [comment]
Since luvit/require@2.0.3 this works without any modifications. Beware that you need luvit/luvit@2.11.5 to get this version of require!
