### ISSUE TITLE
Node.js API incompatibility of hostname in url.parse

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luvit#845]
The Node.js API defines the field `host` as:

> The full lowercased host portion of the URL, including port information.
> Example: 'host.com:8080'

However, the Luvit API sets it to same value as `hostname` [1]:

> Just to be compatible with our code base. Discuss this.

Can this be resolved?

[1] https://github.com/luvit/luvit/blob/master/deps/url.lua#L51

**Comment by rphillips** [comment]
There is a comment in the code base that the hostname = host because of the legacy codebase. I would be fine tweaking this.

**Comment by rphillips** [comment]
could be a double close as well...

**Comment by creationix** [comment]
We should match the node API here.

**Comment by joerg-krause** [comment]
I guess this is fixed in https://github.com/luvit/luvit/commit/49c2a84320967fbe8e0c9495e04939fb6db801d7.
