### ISSUE TITLE
bug caused by https://github.com/luvit/luvit/commit/5e5d0833acc92e911813c2c71c427b51df8bb5fb

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvit#860]
Hi, @creationix 
Here remove global process, https://github.com/luvit/luvit/commit/5e5d0833acc92e911813c2c71c427b51df8bb5fb#diff-b3bd7e7eca363d2f1a751c4ed4d21463R38
but it need in https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua more than one line, just like https://github.com/luvit/luvit/blob/master/deps/stream/stream_readable.lua#L452

So we should make process be in _G, or to modify stream_readable.lua

**Comment by creationix** [comment]
There is still a global process, the one I removed was a different global that only existed in the repl.
