### ISSUE TITLE
How to create a client?

### ISSUE THREAD

**Issue by Miigon** [luvit/luvit#877]
The example "tcp-echo-client.lua":
```lua
local net = require('net')

local client
client = net.createConnection(1234, '127.0.0.1', function (err)
  if err then error(err) end

  print("Connected...")

  -- Send stdin to the server
  process.stdin:pipe(client)

  -- Send the server's response to stdout
  client:pipe(process.stdout)
end)
```
This example send stdin to the server and send response to stdout.How can I send response to a function?

**Comment by creationix** [comment]
If you want to handle the stream, then run it through a stream transform or manually listen for the events.

**Comment by Miigon** [comment]
listen for the events?is it ```Readable.addListener```?

**Comment by Miigon** [comment]
I read Node.js doc and found the solution.
Thanks the node feeling of luvit again.
