### ISSUE TITLE
Compile from source fails on OSX

### ISSUE THREAD

**Issue by mhahn-sighthoundlabs** [luvit/luvit#878]
Followed the steps from here: https://luvit.io/install.html
I had lit already in the path, just in case that matters.
The fallout is here: https://gist.github.com/mhahn-sighthoundlabs/60401e432c6670e533fa

OSX Yosemite (Darwin a4840bcd.local 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64)
clang-602.0.53, make 3.81, cmake 3.4.3

**Comment by creationix** [comment]
Looks like I need to update the documentation there.  Luvi changed it's interface a long time ago.

To build lit using a lit.zip and luvi, you now do:

```sh
luvi lit.zip -- make lit.zip
```

But as you mention already having lit in path, building luvit is simply:

```sh
lit make lit://luvit/luvit
```

**Comment by creationix** [comment]
Also, the `lit update` command will currently build and install `luvit` to the same place you have lit installed, so then all that's needed is `lit update`

**Comment by creationix** [comment]
https://github.com/luvit/luvit.io/commit/57a411fafac79db77b75d4b11f34f4df5d5db409

**Comment by mhahn-sighthoundlabs** [comment]
Thanks for the quick response!

It's still breaking for me however:
https://gist.github.com/mhahn-sighthoundlabs/3b1367e3cd2b991dae85

Have a fresh Lua installation on my system, see bottom of the screen log.

**Comment by creationix** [comment]
I see, that's the wrong zip file for lit.  It should be https://lit.luvit.io/packages/luvit/lit/latest.zip

**Comment by creationix** [comment]
https://github.com/luvit/luvit.io/commit/03ad2041297f3ba72642e6b3de2b75ab1c66dfc6

**Comment by creationix** [comment]
Also I'm curious, why are you building from source and not using the `get-lit.sh` script?  Your platform looks like a normal macbook which we have pre-built luvi binaries built for.

For reference, this is what the [script](https://github.com/luvit/lit/blob/master/get-lit.sh) does:

```sh
#!/bin/sh
set -eu
LUVI_VERSION=2.6.1
LIT_VERSION=3.1.1

LUVI_ARCH=`uname -s`_`uname -m`
LUVI_URL="https://github.com/luvit/luvi/releases/download/v$LUVI_VERSION/luvi-regular-$LUVI_ARCH"
LIT_URL="https://lit.luvit.io/packages/luvit/lit/v$LIT_VERSION.zip"

# Download Files
echo "Downloading $LUVI_URL to luvi"
curl -L $LUVI_URL > luvi
chmod +x luvi
echo "Downloading $LIT_URL to lit.zip"
curl -L $LIT_URL > lit.zip

# Create lit using lit
./luvi lit.zip -- make lit.zip

# Cleanup
rm -f lit.zip
```

**Comment by mhahn-sighthoundlabs** [comment]
All works now, thanks again. Building from source just for the exercise :)

**Comment by creationix** [comment]
Thanks for finding and reporting problems in the docs then :)
