### ISSUE TITLE
Request misses 'end'/'closed' events

### ISSUE THREAD

**Issue by dvv** [luvit/luvit#88]
Test case:

```lua
require("http").create_server("0.0.0.0", 8080, function (req, res)
  req:on('closed', function () p('CLOSED') end)
  req:on('data', function () p('DATA') end)
  req:on('end', function () p('ENDED') end)
  res:finish()
end)
```

One can try `curl`ing http://localhost:8080/ and see no expected events.

The fix is to remove https://github.com/luvit/luvit/blob/master/lib/response.lua#L85 , but I believe this deserves more careful attention.

TIA,
--Vladimir

**Comment by creationix** [comment]
Works now in luvit 2.0.  Here is my updated test program:

```lua
require("http").createServer(function (req, res)
  req:on('data', function () p('DATA') end)
  req:on('end', function () p('ENDED')
    res:finish()
  end)
end):listen(8080, "0.0.0.0")
```

Testing with a curl gives me "data" and "end" events.
