### ISSUE TITLE
where to find "uv.lua" file?

### ISSUE THREAD

**Issue by cylon147** [luvit/luvit#881]
I am getting error that 

`Module uv.lua does not found`

In many dependency files there is 

`local uv = require "uv"`

at beginning of the file.

am i missing something?

**Comment by creationix** [comment]
If you're using luvit or luvi, the `uv` module is built into the C code.  If you're using luajit or lua and the luv bindings as `luv` there is a package on lit called `creationix/uv` that redirects to `luv`.

https://luvit.io/lit.html#author:creationix%20name:uv
