### ISSUE TITLE
Cannot publish package

### ISSUE THREAD

**Issue by LennyPenny** [luvit/luvit#882]
![http://i.imgur.com/REQFSdc.png](http://i.imgur.com/REQFSdc.png)

Any ideas?

**Comment by creationix** [comment]
Make sure your package.lua (or inline metadata) has the name field set properly.

**Comment by LennyPenny** [comment]
I used lit init, so I guess it's probably set
![http://i.imgur.com/qcYgrDM.png](http://i.imgur.com/qcYgrDM.png)

**Comment by squeek502** [comment]
Package names should be of the format `<author>/<package>` (e.g. `luvit/pretty-print`). Would definitely be good to make that error more explicit.

**Comment by LennyPenny** [comment]
Thanks that fixed it!
