### ISSUE TITLE
this should be fix.

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvit#884]
please think this.

because socket maybe keep-alive, so with long life time, but self.socket:on(...) will register event handle every page request, I think the event handle should be in page life time, not connection life time.

```lua
function ServerResponse:initialize(socket)
  Writable.initialize(self)
  local encode = codec.encoder()
  self.socket = socket
  self.encode = encode
  self.statusCode = 200
  self.headersSent = false
  self.headers = setmetatable({}, headerMeta)

  for _, evt in pairs({'close', 'drain', 'end' }) do
    self.socket:on(evt, utils.bind(self.emit, self, evt))
  end
end
```
https://github.com/luvit/luvit/blob/master/deps/http.lua#L112-L124

**Comment by zhaozg** [comment]
ping @creationix and @rphillips

**Comment by creationix** [comment]
Or better, remove the listeners before returning the socket to the keepalive pool?  We should remove the listeners when done anyway right?
