### ISSUE TITLE
url.parse: host = hostname

### ISSUE THREAD

**Issue by squeek502** [luvit/luvit#891]
I started porting over `url.format` and `url.resolve` from node, but ran into a difference that changes how `url.format` would be implemented. 

In node, url.parse returns `host` with the port included, and `hostname` without the port (e.g. `url.parse("http://localhost:3000")` would give `host`=`localhost:3000` and `hostname`=`localhost`), but Luvit sets `host = hostname`, seemingly for backwards compatibility reasons.

https://github.com/luvit/luvit/blob/master/deps/url.lua#L53
```
  host = hostname -- Just to be compatible with our code base. Discuss this.
```

Let me know if I should keep the current Luvit functionality or if I should bring this in line with node.

**Comment by squeek502** [comment]
Seems like probably the functionality should remain the same, as `http` uses the `host` key of parsed urls and does not expect the port to be included.

**Comment by creationix** [comment]
I think moving to the node convention is fine, we'll just need to be careful to not break things.  A major version bump will be a minimum.
