### ISSUE TITLE
Full path not displayed in traceback

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luvit#896]
Currently, luvit's traceback shows strings for the source path. In the sample below, paths are appended with `string`, and in cases where the path is beyond a certain length, it is truncated by `...`.

```lua
Uncaught exception:
[string "bundle:deps/require.lua"]:291: [string "C:/Luvit/Discordia/deps/Discord
ia/classes/dis..."]:6: unexpected symbol near 'local'
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/require.lua"]:291: in function 'require'
        [string "C:/Luvit/Discordia/deps/Discordia/classes/dis..."]:2: in function 'fn'
...
```

This is a result of the custom require module that luvit uses, where ever `loadstring` is called. From the Lua 5.2 manual:

> source: the source of the chunk that created the function. If source starts with a '@', it means that the function was defined in a file where the file name follows the '@'. If source starts with a '=', the remainder of its contents describe the source in a user-dependent manner. Otherwise, the function was defined in a string where source is that string.

So, in `require.lua`, if you append "@" to the path, this fixes half of the issue.

By changing
`local fn = assert(loadstring(data, path))`
to
`local fn = assert(loadstring(data, "@" .. path))`

, the trace becomes:

```lua
Uncaught exception:
[string "bundle:deps/require.lua"]:291: ...vit/Discordia/deps/Discordia/classes/
discord/message.lua:6: unexpected symbol near 'local'
stack traceback:
        [C]: in function 'assert'
        [string "bundle:deps/require.lua"]:291: in function 'require'
        C:/Luvit/Discordia/deps/Discordia/classes/discord/user.lua:2: in function 'fn'
...
```

This solves the issue of required file paths, but it leaves luvi bundled paths untouched. This would presumably be solved by applying a similar adjustment to the `loadstring` call in `luvibundle.lua` in the luvi source, but this is something that I have not been able to properly investigate.

(Shoutout to @SpaceManiac for helping discover a fix.)

**Comment by creationix** [comment]
Thanks for the find.  If I understand correctly, this means that luvit-loader.lua based programs don't have this problem since they use native `dofile` to require files.

**Comment by SinisterRectus** [comment]
That's probably true, since `load` and `loadstring` do not always load a file, but `dofile` is used exlusively for files.

**Comment by SinisterRectus** [comment]
Sorry, keep accidentally closing.

**Comment by creationix** [comment]
New luvit release out with patch to require.  I'll leave this open to remind me to patch luvi as well.

**Comment by squeek502** [comment]
Nice, the truncated paths were bothering me. :+1:

**Comment by creationix** [comment]
Hmm, it seems this introduced bugs around bundle paths.  This latest commit should fix things though.

**Comment by Miigon** [comment]
nice job

**Comment by LoganDark2** [comment]
These also do not display what line in your file triggered the other files to error.

**Comment by Miigon** [comment]
@LoganDark2 error()'s argument 2 can do this.You should check out stack traceback.
