### ISSUE TITLE
How can I get request hostname and request protocol in http handlers

### ISSUE THREAD

**Issue by cyrilis** [luvit/luvit#897]
Hi there, 

How can I get the full url (with protocol and hostname) of the request in request handler function like: 

```lua
http.createServer(function (req, res)
  p(req.protocol) --- nil
  p(req.url) -- /path/without/host
  p(req.headers.host) --- without protocol
  local body = "Hello world\n"
  res:finish(body)
end):listen(1337, '127.0.0.1')
```
Thank you guys for any hint.
BTW, I do love this project very much ❤️

**Comment by creationix** [comment]
Use `url.parse` on the `req.url`.

```lua
local urlParse = require('url').parse

...

p(urlParse(req.url))
```

**Comment by squeek502** [comment]
Correct me if I'm wrong, but isn't the protocol implied by the type of server? Wouldn't it always be `http://` in your case? If so, you could then use the newly added `url.resolve` (in Luvit 2.11.0) to combine `req.headers.host` and `req.url` like so:

```lua
local urlResolve = require("url").resolve
local fullURL =  urlResolve("http://" .. req.headers.host, req.url)
p(fullURL)
```

**Comment by cyrilis** [comment]
@creationix  req.url is a url path, not full url. 
@squeek502 Well, I see. Maybe I should get protocol by environment instead of from request, so that I can get correct "https" if luvit project run behind SSL configed nginx (production environment ). 

Thanks you guys.

**Comment by creationix** [comment]
Correct, it's impossible to get the protocol from the http request *data* alone.  It is possible to get the port and address used by calling `req.socket:getsockname()`.  Also as side effects of the TLS library being used there may be a flag or something unique in TLS requests as opposed to plain TCP connections.

**Comment by creationix** [comment]
I just added a `tls` flag to the virtual socket created by the `secure-socket` library currently used by lit and the coro-* libraries.  Eventually I hope to use this for luvit as well. 
https://github.com/luvit/lit/blob/375b838c20fa957ab302f1b21f703b51e998c89d/deps/secure-socket/biowrap.lua#L28
