### ISSUE TITLE
is Luvit support jsonrpc2.0 call

### ISSUE THREAD

**Issue by Kumar-Patil** [luvit/luvit#900]
Hi All,

I am new to luvit, 

Please let me know is luvit supports jsonrpc2.0 call handling automatically.

If yes please share me the way of calling and getting the response.
url is http:127.0.0.0:9192/
Sample jsonrpc data.
'{"jsonrpc":"2.0","id":1,"method":"discovery","params":{}}'

Thanks&Regards
Santosh Patil

**Comment by creationix** [comment]
Luvit core is very minimal and doesn't have a library for this protocol.  Luvit itself is a great platform for writing RPC protocols and users can publish their libraries to the lit repository. A quick search for rpc shows at least one result that may be useful <https://luvit.io/lit.html#rpc>

**Comment by creationix** [comment]
Also I'm working on another rpc system (not jsonrpc) that's part of the super-agent project. https://luvit.io/lit.html#fife

**Comment by Kumar-Patil** [comment]
Thank you for your input.
