### ISSUE TITLE
is Luvit support socket programing

### ISSUE THREAD

**Issue by Kumar-Patil** [luvit/luvit#902]
HI All,
i am new to luvit,
i have written socket program in lua. it works perfect.
Please find the below code.
local socket = require("socket")
local host = "127.0.0.1"
local port = 9192
local sock = socket.connect(host, port)
local input, recvt, sendt, status
input ='{"jsonrpc":"2.0","id":1,"method":"discovery","params":{}}'  --io.read()
if #input > 0 then
    local response  = sock:send(input)
    print(response)
end
local response = ''
local res, status, partial  = sock:receive(512*3+95)
response = response .. res
--local result = json.stringify(response)
--print(result.result.meterVersion)
print("Response")
print(response)

Can i write same thing in luvit ?
If yes can you please help me to do it in luvit.

Thanks in advance.
Santosh Patil

**Comment by creationix** [comment]
Yes luvit has built-in support for socket programming. You can't use the luasocket library, but rather the TCP interface in libuv.  Builtin to the luvit metapackage has a "net" module that like the one in node.js.  Letely I've been heavily using the "coro-net" package which offers a friendly coroutine based interface to TCP and unix sockets.

**Comment by Kumar-Patil** [comment]
Thanks for providing details..I have plan to use net module file. If possible can you please share me the  some sample code how to use the socket..take above as sample example. I am New to luvit..

**Comment by Miigon** [comment]
You can have a look in [the luvit examples](https://github.com/luvit/luvit/tree/master/examples).
_Equivalent codes of your codes:_
```lua
local net = require "net"

local host = "127.0.0.1"
local port = 9192

local client
client = net.createConnection(port, host, function (err)
  if err then error(err) end

  local input = '{"jsonrpc":"2.0","id":1,"method":"discovery","params":{}}'
  client:write(input)

  client:on("data",function(data)
    print(data)
    client:shutdown()
  end)
  
end)
```
Notice that luvit only has non-blocking connection supported so that it's a quite different from luasocket.If you don't like callbacks,try to wrap it with coroutine or use coro-net module.
