### ISSUE TITLE
luvit on openwrt?

### ISSUE THREAD

**Issue by ralphtheninja** [luvit/luvit#903]
Has anyone thought about making this available on OpenWRT or have there been any discussions around that?

**Comment by creationix** [comment]
It might be a little heavy for that platform.  The hardest parts will be libuv, luajit, and openssl.  If you can get all those to build on there, it should work.

**Comment by creationix** [comment]
Also as I understand OpenWRT is just a linux distribution.  So it matters a lot exactly what hardware you're targeting.

**Comment by ralphtheninja** [comment]
> Also as I understand OpenWRT is just a linux distribution. So it matters a lot exactly what hardware you're targeting.

I know that they use lua a lot on OpenWRT so it should be a really good match to get it working on architectures like mips etc.

**Comment by milani** [comment]
I prepared luajit/luv/luvi packages for openwrt. You can find them here: https://github.com/milani/packages/tree/luvi. 

You will be able to run luvit packages with luvi. The only problem is that on MIPS 32 cpus, you will get illegal instructions error (https://github.com/LuaJIT/LuaJIT/issues/178). The solution is to add the following to https://github.com/milani/packages/commit/e8db17c18b11b520a4075615f1f19b32849749da#diff-ab9329820ef7a9b3133113332681d643R54:

```
CFLAGS := $(filter-out -mips16 -minterlink-mips16,$(CFLAGS))
CXXFLAGS := $(filter-out -mips16 -minterlink-mips16,$(CXXFLAGS))
AS := $(filter-out -mips16 -minterlink-mips16,$(AS))
```

**Comment by zischwartz** [comment]
@milani is that package still available anywhere?

**Comment by milani** [comment]
@zischwartz I pushed the branch again according to new openwrt guidelines. Find it [here](https://github.com/milani/packages/commits/luvi). But my previous PRs to openwrt are not merged. So you have to grab dependencies manually from other branches: `luv` and `luajit`.
