### ISSUE TITLE
How to exit script?

### ISSUE THREAD

**Issue by LoganDark2** [luvit/luvit#905]
How do you exit a script from inside the script?

**Comment by squeek502** [comment]
`process:exit()`

**Comment by LoganDark2** [comment]
What is `process`?

**Comment by LoganDark2** [comment]
Is it `client`?

**Comment by LoganDark2** [comment]
@squeek502

**Comment by squeek502** [comment]
Not sure what you're asking. `process` is a global variable that is set by Luvit to the value of `require('process').globalProcess`. 

If you're in the Luvit repl, you can exit using Ctrl + C or typing `process:exit()` and hitting enter

In a Luvit script, you can always exit by calling `process:exit()`. For example:

test.lua
```lua
print("executing")
process:exit()
print("exited before this")
```
will output:
```
> luvit test.lua
executing
```

**Comment by LoganDark2** [comment]
ok
