### ISSUE TITLE
How do I accept commands from the terminal?

### ISSUE THREAD

**Issue by LoganDark2** [luvit/luvit#907]
When I start my program using `luvit main`, I am given the ability to enter commands into the terminal. Is there any way to catch these, and pass them to the script?

**Comment by LoganDark2** [comment]
@creationix

**Comment by squeek502** [comment]
`luvit` when run without arguments [starts the Luvit repl](https://github.com/luvit/luvit/blob/master/main.lua#L121-L139) using [the `repl` module](https://github.com/luvit/luvit/blob/master/deps/repl.lua), which in turn uses [the `readline` module](https://github.com/luvit/luvit/blob/master/deps/readline.lua).

You can start the Luvit repl after executing a script by using the `--interactive` flag. Example: `luvit --interactive test.lua`

You can also use the `readline` module to get user input and do whatever you want with it. Here's some example code that shows the basics of how to use `readline` to continually get user input:

```lua
local readline = require('readline')

local prompt = "> "
local history = readline.History.new()
local editor = readline.Editor.new({stdin = process.stdin.handle, stdout = process.stdout.handle, history = history})

local function onLine(err, line, ...)
	if line then
		print("You entered: " .. line)
		editor:readLine(prompt, onLine)
	else
		process:exit()
	end
end

editor:readLine(prompt, onLine)
```

**Comment by LoganDark2** [comment]
Thanks!
