### ISSUE TITLE
What's the best service for hosting a full-time application for free?

### ISSUE THREAD

**Issue by LoganDark2** [luvit/luvit#908]
I need to host a full-time application, and I need root access to a full-time always-on server. Yet I do not own a server, and I have no money to spend. I would prefer a Linux or Mac OS X (or macOS in the future) as the OS. I need full root command line access, and if possible, an IDE.

I've tried Cloud9, but it kills all running processes after 2 hours of not being accessed, and after 7 hours it shuts down the server completely. I've tried OpenShift, but they don't give me root access and to run my app, I need full root access.

So, after all this, I've decided to ask it on StackOverflow. Unfortunately, this got my account blocked from posting questions, and nobody answered...

But anyway, please list all pros and cons of the service you recommend when posting an answer.

I don't need much disk space or RAM, as the application is fairly small, and I will only use free services.

**Comment by creationix** [comment]
Sorry, I don't know of any free hosting services that give you unlimited process uptime and root.

I do know you can get pretty good VPS services these days for as low as $5/month.  Those tend to give you root inside a virtual machine.

**Comment by Miigon** [comment]
VPS is a good choice.If you need good performance,try Microsoft Azure

**Comment by daurnimator** [comment]
You can get 12 months free from AWS.

Otherwise $5 a month for a very capable VPS from e.g. vultr or digital ocean should be affordable for anyone. If you're studying you can get some free digital ocean credits from github.

**Comment by LoganDark2** [comment]
I don't want a free trial lmfao

**Comment by LoganDark2** [comment]
azure requires a credit card

**Comment by Miigon** [comment]
There is no such thing as a free lunch.the easiest and cheapest way is VPS.Or you can try to build a server machine yourself and run it 24hours.

**Comment by Miigon** [comment]
I did so,too. :)

**Comment by LoganDark2** [comment]
:(
