### ISSUE TITLE
How do I store a table in a file?

### ISSUE THREAD

**Issue by LoganDark2** [luvit/luvit#910]
How do you store a table of variables in a file on quit and then convert it back into a table on startup?

**Comment by LoganDark2** [comment]
Nevermind, the JSON component can do this.

**Comment by LoganDark2** [comment]
Reopened because I can't find out how to r/w from files.

**Comment by LoganDark2** [comment]
Also I'd also like to know how to do this anyway, as I don't want to figure it out myself :P

**Comment by creationix** [comment]
There are lots of examples here that will get you going. https://github.com/luvit/luvit/tree/master/examples

**Comment by LoganDark2** [comment]
I just want to read an entire file and store it in a string, and write an entire string to a file, overwriting its contents.

**Comment by LoganDark2** [comment]
The FS api is waaaay too complicated.

**Comment by IZEDx** [comment]
You can find everything you need here: https://github.com/luvit/luvit/blob/master/examples/fs-basic.lua

Most important part is the end, I changed it a little bit for easier understand though:

    -- data is the string of content
    local data = "Test Content"
   
    fs.writeFile("test.txt", data, function (err)
        if (err) then return end

        fs.readFile("test.txt", function (err, data)
          if (err) then return end
          print(data)
        end)
    end)

**Comment by LoganDark2** [comment]
And read?

**Comment by LoganDark2** [comment]
Oh nvm xD
