### ISSUE TITLE
make install: regression "No rule to make target `luvit'"

### ISSUE THREAD

**Issue by ilovezfs** [luvit/luvit#911]
86a06bf4ee05b39e098d9845365d5a330f31360b seems to have introduce a regression that causes `make install` to fail with
```
make: *** No rule to make target `luvit', needed by `install'.  Stop.
```

Adding back in
```
luvit: lit $(APP_FILES)
	./lit make
```
fixes it, but I'm wondering if something else is expected to run `./lit make` now? As far as I can tell, no
```
bash-3.2$ grep -r make .|grep lit
Binary file ./.brew_home/.litdb.git/cache/cc5df6cfa3476f2d4c5c097ad2448c4e64b49eab/luvi matches
./README.markdown:to lit, just make sure to keep them in sync.  One way to do this is to `rm -rf
./README.markdown:packages from lit.  Check the diff carefully to make sure you're not undoing
./examples/custom-binary/Makefile:	lit make .
Binary file ./lit matches
./make.bat:IF NOT EXIST lit.exe CALL make.bat lit
./make.bat:lit.exe make
```

**Comment by creationix** [comment]
Is this still a problem?  I can't reproduce this on latest master.

```sh
git clone --recursive git@github.com:luvit/luvit.git
cd luvit
make test
```

Downloads luvit and lit using the get-list.sh script, builts lit and then builds luvit using lit and runs the unit tests.

**Comment by ilovezfs** [comment]
Yeah I tested master and the tag. It does not build the luvit binary.
```
# Starting Test: url - should resolve /foo/bar/ to .
ok 223 url - should resolve /foo/bar/ to .

# Starting Test: url - should resolve /foo/bar/ to ..
ok 224 url - should resolve /foo/bar/ to ..

# Starting Test: url - should resolve foo/bar to ../../../baz
ok 225 url - should resolve foo/bar to ../../../baz

# Starting Test: url - should resolve foo/bar/ to ../../../baz
ok 226 url - should resolve foo/bar/ to ../../../baz

# Starting Test: utils - utils
ok 227 utils - utils

# Starting Test: windows-long-path - fs windows long path
ok 228 windows-long-path - fs windows long path
# All tests passed
iMac-TMP:luvit joe$ ls -1
ChangeLog
LICENSE.txt
Makefile
NOTICE.txt
README.markdown
Vagrantfile
appveyor.yml
bench
deps
examples
init.lua
lit
luvi
main.lua
make.bat
package.lua
tests
tools
```

**Comment by creationix** [comment]
Oh, I understand now.  Make test doesn't depend on it anymore, but install does.  Fix incoming.

**Comment by creationix** [comment]
Sorry for the misunderstanding.  43f02b03912b4e007f08e0aa51833668441d401f should fix things. (It may break my CI again, but that needs the root cause fixed anyway)

**Comment by ilovezfs** [comment]
Thanks. Another problem while I have your attention :)
https://github.com/Homebrew/homebrew-core/pull/2313
```
# Starting Test: readline - readline Editor:onKey
  ...vit-20160622-4972-10460gc/luvit-2.11.1/deps/readline.lua:471: attempt to call method 'set_mode' (a nil value)
  stack traceback:
  	...vit-20160622-4972-10460gc/luvit-2.11.1/deps/readline.lua:471: in function 'readLine'
  	...160622-4972-10460gc/luvit-2.11.1/tests/test-readline.lua:31: in function 'fn'
  	...it-20160622-4972-10460gc/luvit-2.11.1/tests/libs/tap.lua:77: in function <...it-20160622-4972-10460gc/luvit-2.11.1/tests/libs/tap.lua:64>
  	[C]: in function 'xpcall'
  	...it-20160622-4972-10460gc/luvit-2.11.1/tests/libs/tap.lua:64: in function 'run'
  	...it-20160622-4972-10460gc/luvit-2.11.1/tests/libs/tap.lua:165: in function 'tap'
  	...p/luvit-20160622-4972-10460gc/luvit-2.11.1/tests/run.lua:42: in function 'fn'
  	[string "bundle:deps/require.lua"]:309: in function 'require'
  	...te/tmp/luvit-20160622-4972-10460gc/luvit-2.11.1/main.lua:118: in function 'main'
  	...te/tmp/luvit-20160622-4972-10460gc/luvit-2.11.1/init.lua:49: in function <...te/tmp/luvit-20160622-4972-10460gc/luvit-2.11.1/init.lua:47>
  	[C]: in function 'xpcall'
  	...te/tmp/luvit-20160622-4972-10460gc/luvit-2.11.1/init.lua:47: in function 'fn'
  	[string "bundle:deps/require.lua"]:309: in function <[string "bundle:deps/require.lua"]:265>
not ok 148 readline - readline Editor:onKey
```
Full log:
https://gist.github.com/ilovezfs/12b1ff461c8340c575b220fef84b2cf1

I can't reproduce the problem locally but it's killing our CI on all 3 nodes (el capitan, yosemite, and mavericks). Any idea what the cause is? Maybe that test can be yanked if it's not CI friendly?

**Comment by creationix** [comment]
I'll bet it's because stdin in your CI environment is not a TTY and luvit is using FD 0 as a normal pipe.  We should configure that test to skip itself if there is no TTY on stdin.

**Comment by ilovezfs** [comment]
Yup, that makes sense.

**Comment by creationix** [comment]
Let me know if this fixes it and I'll tag/publish a new luvit release to github/lit.

**Comment by ilovezfs** [comment]
@creationix OK, CI triggered with https://github.com/Homebrew/homebrew-core/pull/2313/files so we'll see :)

**Comment by ilovezfs** [comment]
@creationix It's :green_apple:

**Comment by ilovezfs** [comment]
Woo hoo https://github.com/luvit/luvit/releases/tag/2.11.2
Thanks!!

**Comment by creationix** [comment]
@ilovezfs there was some confusion around releases (I had a laptop die with some changes not pushed to master).  Please use 2.11.3 that has all the lost changes restored.

**Comment by ilovezfs** [comment]
Cool

**Comment by ilovezfs** [comment]
@creationix I think the tag still needs to be pushed.

**Comment by creationix** [comment]
@ilovezfs done!
