### ISSUE TITLE
Can't hide input with Editor:readline()

### ISSUE THREAD

**Issue by LoganDark2** [luvit/luvit#913]
The `readline` API always shows input as plaintext. This is an issue as entering passwords can be very insecure. For example if someone's looking over your shoulder, or if someone sees your terminal logs, etc.

The solution is to allow the calling of `Editor:readline()` with an optional third argument, a string, which any entered character will be displayed as.

**Comment by LoganDark2** [comment]
@creationix

**Comment by creationix** [comment]
This would be a neat feature.  I know node.js supports this somehow in it's readline library.  Could you find where this is done in node or npm?

**Comment by squeek502** [comment]
Doesn't look like this is supported in Node itself, but is in some node packages:

- https://github.com/anseki/readline-sync (`hideEchoBack` option)
- https://github.com/npm/read (`silent` option)

Some StackOverflow answers:

- http://stackoverflow.com/questions/4708787/get-password-from-input-using-node-js
- http://stackoverflow.com/questions/24037545/how-to-hide-password-in-the-nodejs-console

**Comment by creationix** [comment]
I see, thanks @squeek502!

**Comment by LoganDark2** [comment]
I might want to modify the readline library myself to allow this feature.

**Comment by Miigon** [comment]
@creationix Would you consider to add this feature to luvit?
It's quite good and useful although nodejs don't have it.

**Comment by creationix** [comment]
I would if I knew how it was implemented.  I guess I could just have a flag where the echo wasn't echoed or echoed as dots or something.

**Comment by LoganDark2** [comment]
Have a flag where every 1 character could be replaced by a certain string, and also a flag that doesn't print any input

**Comment by creationix** [comment]
This commit works for single characters.  It somewhat works for other lengths, but weird things happen if you use the arrow keys or backspace.

@LoganDark2 does this work for you?

**Comment by LoganDark2** [comment]
you should work on fixing the arrow keys and backspace for those.

and also, please work on an option where no input is displayed.

**Comment by LoganDark2** [comment]
here's my fixes for arrow keys and backspace:

when backspacing, set the cursor back in increments of the length of the display variable, and...

when using arrow keys, go left and right in increments of the length of the display variable as well.

**Comment by creationix** [comment]
@LoganDark2 It looks like all the code goes through a central place in refreshLine, so it was pretty easy to fix with this latest commit.  If you don't want to show anything at all, simply pass `''` as your cover.

**Comment by LoganDark2** [comment]
thanks, it's not the solution i exactly wanted (not moving the cursor at all), but it's fine

**Comment by creationix** [comment]
Are you sure it's not what you want?  If you pass in an empty string, the cursor doesn't move.

**Comment by LoganDark2** [comment]
Oh, I didn't realize that. Thanks!

**Comment by creationix** [comment]
I just published the updated readline module to lit if you're using it directly.  Otherwise it will come with the next luvit release.
