### ISSUE TITLE
How to make sure the main thread waits for the called function to complete.

### ISSUE THREAD

**Issue by JoeBmc** [luvit/luvit#921]
Hi,
I am new to lua & luvit. 
Please help with the below issue. The main execution sequence does not wait for getVersion() to complete.

--global variable.
version = nil
print('Before fn call')
getVersion()
if(version == '1.2') then
   --do something
else
  -- do something else
end
print('version=' .. version)
print('Done')

local function getVersion()
  print('Inside getVersion')
  ....
  ....
  local req = http.request(options, function (res)
                print("Inside request")
                res:on('data', function (data)
                     ---get the version and assign to global variable version.
                     print('version:' .. version)
                end)
              print('After the execution')
  end)
  req:done()
end

---

Below is the console output when I run the same.

Before fn call
Inside getVersion
version=nil
Done
Inside request
version:1.2
After the execution

I want to make sure the getVersion fn is completed before continuing with the main thread.
I tried a method fiber.wait(fn()), but did not workout.
Is this the right method, or do we have any other way to get it done.

Any help regarding the same is much appreciated.

Thanks & regards,
Joe

**Comment by JoeBmc** [comment]
If fiber.wait() is the right method, a small example will be of great help.

**Comment by creationix** [comment]
Remember that luvit is based on a non-blocking event model.  This means that normally you can't wait for I/O to finish.

It is possible, however, using coroutines to pause the running coroutine.  Then other code and events can be handled.  When the result comes through the event loop you can resume the coroutine.  In effect, it will appear blocking for that thread, but not block the main thread.  You can never block the main thread with anything other than libuv's own uv.run().

**Comment by creationix** [comment]
The built-in libraries in the legacy luvit package are ported from node.js where there are no coroutines.  I would recommend using the newer coroutine based APIs as used by lit.  For example, the [coro-http](https://github.com/luvit/lit/blob/d80d38407a9234988f2d70d49275b6eead120f9b/deps/coro-http.lua#L104-L186) library can do what you want.

```lua
local request = require('coro-http').request

coroutine.wrap(function ()
  local res, body = assert(request("GET", url))
  p(res, body)
end)()
```

**Comment by JoeBmc** [comment]
Thanks for your help. 
Let me try with coroutines.

**Comment by JoeBmc** [comment]
I was trying coro-http as you have mentioned above.
Can you please help me on the below error.

local corohttp = require('coro-http')
local url = require('url')

local getresult = coroutine.wrap(function()
    local myurl = url.parse("http://localhost:8983/solr/admin/info/system", "wt=json")
    --local myurl = url.parse("https://localhost:8983/solr/admin/info/system?wt=json", "")
    print(myurl.protocol)
    print(myurl.host)

**Comment by JoeBmc** [comment]
I was trying coro-http as you have mentioned above.
Can you please help me on the below error.

local corohttp = require('coro-http')
local url = require('url')

local getresult = coroutine.wrap(function()
local myurl = url.parse("https://localhost:8983/solr/admin/info/system?wt=json", "")

print(myurl.protocol)
print(myurl.host)
print(myurl.port)
print(myurl.pathname)
print(myurl.search)
print(myurl.query)

local res, body = assert(corohttp:request("GET", myurl))
print(res)
end)

--Main function
getresult()


--Result on console
http
localhost
8983
/solr/admin/info/system
?wt=json
table: 0x415b87c8
lib/luvit/luvit.lua:297: /root/lua/solr-plugin-25082016/init.lua:142: /root/lua/solr-plugin-25082016/modules/coro-http.lua:46: Not a valid http url: GET
stack traceback:
        [C]: in function 'getSolrVersion'
        /root/lua/solr-plugin-25082016/init.lua:142: in function 'createPollers'
        /root/lua/solr-plugin-25082016/init.lua:156: in function 'fn'
        lib/luvit/module.lua:94: in function 'myloadfile'
        lib/luvit/luvit.lua:409: in function <lib/luvit/luvit.lua:297>
        [C]: in function 'xpcall'
        lib/luvit/luvit.lua:297: in main chunk
        [C]: in function 'require'
        [string "    local path = require('uv_native').execpat..."]:1: in main chunk
WARNING: forgot to close luv_tty lhandle=0x415c1db8 handle=0x2c93570

Note:-
I am using a legacy version of the luvit/url.lua, or is it with the format of url string provided.

thanks,
Joe

**Comment by creationix** [comment]
Here is an example of using the coroutine based http client as used internally in lit to get github public keys https://github.com/luvit/lit/blob/master/libs/github-request.lua#L42

**Comment by creationix** [comment]
So there are two problems I see right away with your code.  One you're calling the function in method mode (with `:` instead of `.`), this injects the `http` module as your first arg displacing the `"GET"` method to be interpreted as the url.  Also your url should probably just be a string and let the coro-http library parse it the way it wants to.

**Comment by JoeBmc** [comment]
Please let me know where can I find the source code for latest uv.lua. As I have mentioned we have a legacy copy of the luvit library and I came across an issue where it cant find uv.getaddrinfo(). The legacy file does not have this function.

**Comment by creationix** [comment]
The uv bindings are now at https://github.com/luvit/luv
You can see all the exposed functions and methods at https://github.com/luvit/luv/blob/master/src/luv.c

**Comment by JoeBmc** [comment]
I created a new luvit executable from the latest luvit by locally building the same.
$luvit init.lua
I use the above command to execute the code.
Facing some issues with resolving the uv.lua which was available with legacy. I have gone through the new bindings you have mentioned above - luv & luv.c but cannot find the required code.

Legacy code.
local hrtime = require('uv').Process.hrtime

Error
       attempt to index field 'Process' (a nil value)

What will be the equivalent for the above line of code in new luvit implementation.
Any help regarding the same is appreciated.

**Comment by squeek502** [comment]
```
local hrtime = require('uv').hrtime
```

**Comment by JoeBmc** [comment]
Thanks that worked. 
Do we have some API reference for the methods / fields exposed by each of the libraries.
I am not able to find anything related to - require('os'). Which is the file associated with it and where can we find the code / documentation.

**Comment by squeek502** [comment]
`'os'` is a native Lua library, so requiring it is not necessary (although it may have been in legacy Luvit). See the Lua docs: https://www.lua.org/manual/5.1/manual.html#5.8

**Comment by JoeBmc** [comment]
Yes, I was referring to the legacy one we had in luvit-1.0. The code os.hostname() is not available now. Even the documentation is obsolete.  - https://github.com/develephant/luvit-docs/wiki/os
This was available in node API but not available with luvit 2.0. - https://millermedeiros.github.io/mdoc/examples/node_api/doc/os.html
Do we have an equivalent code for os.hostname().

**Comment by rphillips** [comment]
@JoeBmc you can the FFI to get the hostname: https://github.com/virgo-agent-toolkit/rackspace-monitoring-agent/blob/master/hostname.lua

**Comment by creationix** [comment]
Luajit's `jit` and `ffi` built-in libraries also export `os` and `arch`.

Simply open up a luvit repl and type `jit` to see what's in there.

```lua
$> luvit                                                              
Welcome to the Luvit repl!
> jit
{ arch = 'x64', version = 'LuaJIT 2.1.0-beta2', version_num = 20100,
  status = function: builtin#149, on = function: builtin#146, os = 'OSX',
  off = function: builtin#147, flush = function: builtin#148,
  attach = function: builtin#150, opt = { start = function: builtin#162 } }
>
```
