### ISSUE TITLE
Repl didn't do backspace correctly on multi-byte characters

### ISSUE THREAD

**Issue by Miigon** [luvit/luvit#924]
@creationix 
This happened when I typed some multi-byte characters (such as chinese or japanese) and pressed backspace.

It will only delete last one byte of the character,not all of them(Unicode said they are 2 or 3 bytes)
so it will be...

```
> 中文
Length is 6
```

... and press backspace

```
> 中��
Length is 5
```

I must press backspace twice or three times to delete all bytes of a character.
The main issue is to get the actually length of each character.I think this can be fixed by adding a utf8 wrapper.
btw,this also cause the position of cursor to be wrong.

**Comment by creationix** [comment]
Tricky problem.  I wonder how hard it is to just know how wide each utf8 character is and how many bytes is requires.

**Comment by Miigon** [comment]
If the first 1 bit of the byte is `0`,that character is 1 byte width and this is the first byte.
If the first 2 bit of the byte is `10`,that byte is not the first byte of a character
If the first 3 bit is `110`,that character is 2 byte width and this is the first byte
If the first 4 bit is `1110`,that character is 3 byte width and this is the first byte
If the first 5 bit is `11110`,that character is 4 byte width and this is the first byte
If the first 6 bit is `111110`,that character is 5 byte width and this is the first byte

I think we can parse the text we get with `bit` library and store each character with an array.

btw:nodejs don't have this problem because javascript already do this.

**Comment by creationix** [comment]
Sounds like a plan!  I'm busy today, but I can try to get to this later if you don't beat me to it.

**Comment by creationix** [comment]
Now the other problem is knowing how wide characters physically are, but having a correct character count gets us 90% there.

**Comment by Miigon** [comment]
Okay.

**Comment by Miigon** [comment]
I've fix this bug.But the problem is the processing of characters takes too much time.
I will upload the codes with a pull-request a few days later.

**Comment by cyrilis** [comment]
Hi there, I found some patterns that can count UTF8 characters. Maybe this will help? 

Count utf8 length:
```lua
> _, utf8Count = ("qewr#$%^&*你好：“[>"):gsub("[^\128-\193]","")
> utf8Count
=> 16
```
Or get every UTF8 character:
```lua
> ("qewr#$%^&*你好：“[>"):gsub("([%z\1-\127\194-\244][\128-\191]*)", function(...)p(...)end)
'q'
'e'
'w'
'r'
'#'
'$'
'%'
'^'
'&'
'*'
'\228\189\160'
'\229\165\189'
'\239\188\154'
'\226\128\156'
'['
'>'
=> 'qewr#$%^&*\228\189\160\229\165\189\239\188\154\226\128\156[>'	16
```
