### ISSUE TITLE
about support chinese file path 

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvit#925]
A file with Chinese charset name, don't work with fs.readFileSync and fs.other api.

```lua
-- encoding: asni
local path='中文.txt'
p('path',path)
local f = assert(io.open(path))  --works
local ctx = f:read('*a')
f:close()
p('content',ctx)

local fs = require'fs'
ctx,err = fs.readFileSync(path) --fail, not found
p(ctx,err)
```

if convert path to utf-8, it will work

**Comment by creationix** [comment]
Lua strings don't have any encoding.  The string will have whatever encoding is in your source file between the quotes.  If your filesystem uses another encoding it won't match.

**Comment by zhaozg** [comment]
I means thant path pass to  io.open will auto convert to utf-8,but fs.api need do convert by myself.

**Comment by Miigon** [comment]
Save your source file with UTF-8 encoding.

**Comment by creationix** [comment]
@zhaozg strange, I wonder how lua is doing that then because there is encoding information in lua strings, they are simply 8-bit binary data.

**Comment by Miigon** [comment]
@zhaozg 
Are you using Windows?
This is the `io.open` implementation of luajit(which is used by luvit)
```c
// src/lib_io.c
static IOFileUD *io_file_open(lua_State *L, const char *mode)
{
  const char *fname = strdata(lj_lib_checkstr(L, 1));
  IOFileUD *iof = io_file_new(L);
  iof->fp = fopen(fname, mode); // ***THIS LINE***
  if (iof->fp == NULL)
    luaL_argerror(L, 1, lj_str_pushf(L, "%s: %s", fname, strerror(errno)));
  return iof;
}
```
You will find that luajit just simply called `fopen` to open a file.
  
And this is the **Windows version** libuv implementation of `uv_fs_open`(The core of `fs.openSync()`)
(https://github.com/libuv/libuv/blob/master/src/win/fs.c#L486)
```c
// src/win/fs.c
  file = CreateFileW(req->file.pathw,
                     access,
                     share,
                     NULL,
                     disposition,
                     attributes,
                     NULL);
```
You can find that libuv called `W` suffixed Win32 API,which means that api uses Unicode for strings,and `fopen`'s encoding is depended on your compiler(on Windows it's mostly ansi without settings manually).
This is the reason for which it's "not found" when you give an ansi encoding path to `fs.readFileSync()`.
  
On *nix,libuv called system api `open` and luajit called `fopen`,both them are expecting a Unicode path.
So,if you run this script on *nix,Neither `fs.open()` nor `io.open()` can find the file!
  
BEST to save your file with Unicode encoding,and it will be no problem.

**Comment by zhaozg** [comment]
thanks, that's low layer limit
