### ISSUE TITLE
Plans to move existing NPM modules to Lit?

### ISSUE THREAD

**Issue by darmie** [luvit/luvit#927]
I am having issues installing existing Luvit NPM modules, do you have any plans of migrating them to Lit? 

for example Luvit-base64 wouldn't compile.

**Comment by creationix** [comment]
There are no plans, no.

**Comment by creationix** [comment]
In fact, I was not even aware that there were that many luvit packages on npm.

**Comment by cyrilis** [comment]
@darmie NPM [was](https://groups.google.com/forum/#!topic/luvit/7uDZLgo_lRk) a optional package manager for Luvit in the old days. (before [lit](https://github.com/luvit/lit) went on line.)

[Lit](https://github.com/luvit/lit) is offical package manager now 😄 .

If you need base64, you can use snippets in [this wiki page](https://github.com/luvit/luvit/wiki/Snippets),
or use openssl : 
```lua
local openssl = require("openssl")

local a = "123"
-- encode
local b = openssl.base64(a, true)  --- 'MTIz'
-- decode
local c = openssl.base64(b, false) --- '123'
```

**Comment by squeek502** [comment]
There's also the Lua implementation that Lit uses: https://github.com/luvit/lit/blob/master/deps/base64.lua

It's published to lit as creatonix/base64: https://luvit.io/lit.html#name:base64
