### ISSUE TITLE
Callback parameter type issue during a socket error.

### ISSUE THREAD

**Issue by JoeBmc** [luvit/luvit#931]
I was using legacy Luvit and in the process of migrating to Luvit 2.0. I am facing below issue with socket creation  callback during the error.
I have a server where the application connects to fetch some data. When the server is down - 'Connection refused error' should be throw.

Code:
 net = require('net')
 self.socket = net.createConnection(self.port, self.host, callback)
 self.socket:on('error', function (err) self:emit('error', 'Socket error: ' .. err.message) end)

In legacy the parameter returned in function(err) was a table (object)
but in Luvit 2.0, I get a string - error message.

Any idea whether something changed. Or is there something else which I am doing wrong.

**Comment by JoeBmc** [comment]
To make it clear
self.socket:on('error', function (err) self:emit('error', 'Socket error: ' .. type(err)) end)

Legacy
    output ->Socket error: table
Luvit 2.0
   output -> Socket error: string

**Comment by rphillips** [comment]
This is probably an oversight. I bet we could patch the following line to fix the issue: https://github.com//luvit/luvit/blob/149f01ae8a33e17bb421bffab108a49aa92f89c5/deps/net.lua#L244

**Comment by JoeBmc** [comment]
@rphillips - Sorry, I still did not understand how it can be fixed.

Is there a way to make the application pickup the modified net.lua which I have placed in the libs sub-folder than the one bundled with the luvit executable. I use the command $luvit application.lua to run the same.

**Comment by squeek502** [comment]
I believe all error messages changed to strings in Luvit 2.0. In legacy Luvit, errors would be [an instance of the Error class](https://github.com/luvit/luvit/blob/legacy/lib/luvit/core.lua#L369-L379), but most usage of the Error class was removed in 2.0, although [there are still some instances](https://github.com/luvit/luvit/search?utf8=%E2%9C%93&q=%22Error%3Anew%22&type=Code).

Note that you should be able to safely use `tostring(err)` on both [an Error instance](https://github.com/luvit/luvit/blob/master/deps/core.lua#L352-L354) or a string to get the string value of the error.

**Comment by JoeBmc** [comment]
Thanks @rphillips & @squeek502 .
Let me see if I can use toString() and overcome the issue.
