### ISSUE TITLE
How to we call series of http request in luvit

### ISSUE THREAD

**Issue by Kumar-Patil** [luvit/luvit#938]
Hi All,

I am new to luvit, Can some one  please suggest me write a synchronous of http request and response handling.
1.  I am depended on first http response, but it is going on async way. How do i call series of request call in luvit. Plz help me

**Comment by rphillips** [comment]
The mailing list would be the first place to start. you will probably want to look at [luvit-async](https://github.com/virgo-agent-toolkit/luvit-async).
