### ISSUE TITLE
Inherit globals in new thread

### ISSUE THREAD

**Issue by milani** [luvit/luvit#943]
Isn't it possible for threads to inherit globals like `package`? It is a pain to load all modules again in the new thread.

**Comment by squeek502** [comment]
Not sure what you mean. This seems to work fine for me:

```lua
local test = require('test-require')

print(_G)
print(package.loaded['test-require'])

local co = coroutine.wrap(function()
	print("in coroutine:")
	print(_G)
	print(package.loaded['test-require'])
end)

co()
```

output:

```
table: 007FE048
hello
in coroutine:
table: 007FE048
hello
```

**Comment by milani** [comment]
Lua coroutines work fine. The issue is about uv threads. Here is an example:

```
local thread = require('thread')
local thr = thread.start(function()
  --thread module is undefined here and should be required again.
end)
thr:join
```

**Comment by creationix** [comment]
I don't think we want to force the overhead of all the luvit globals upon every thread created.  It should fairly easy to wrap the thread API with one that does inject the luvit default globals.

See this example for a way to create the luvit globals. https://github.com/luvit/luvit/blob/master/examples/custom-binary/main.lua
