### ISSUE TITLE
thread.start should allow arguments to be passed to function

### ISSUE THREAD

**Issue by MrTeenageParker** [luvit/luvit#949]
I noticed in the documentation it shows that threads accept a second argument. I looked at the source and noticed it has no limit on arguments.

The second argument should also be allowed to pass arguments to the function, to allow something like this:

```
local function test(arg1,arg2)
    return arg`1 + arg2
end

thread.start(function_name, arg1, arg2)
```

Of course the first portion of this issue is a must for me as I require that arguments be passed to the function. Either arguments, a table with arguments, or a metatable to allow for custom environments for the function in the thread to allow further customization would be amazing.

Also a great possibility is that the thread, if taking too long or stalls completely, gives the ability to be terminated. This is especially great for what I plan on using luvit for.

**Comment by squeek502** [comment]
That's exactly how it works.

```lua
local thread = require("thread")

local function test(arg1, arg2)
	print(arg1 + arg2)
end

local thr = thread.start(test, 5, 6)
thr:join()
```

Output:
```
>luvit test-thread.lua
11
```

**Comment by MrTeenageParker** [comment]
Whenever I pass anything other than a string to it (my particular function requires a table) it errors saying that the object type isn't supported. 

That's why I asked this question.

**Comment by MrTeenageParker** [comment]
so something like this:

```
local function test(arg1)
    print(arg1) -- print table
end

thread.start(test, {'item1', 'item2'})
```

returns this:

`Error: thread arg not support type 'table' at 4`

**Comment by ryanplusplus** [comment]
Can't you simply create a wrapper function to pass the argument? I'm not sure why this needs to be directly supported by `luvit` (though it's odd that it supports strings doesn't support tables).

```lua
local function test(arg1)
    print(arg1) -- print table
end

thread.start(function()
   test({'item1', 'item2'})
end)
```

**Comment by MrTeenageParker** [comment]
I didn't think of doing this. I can certainly try it, but threads from what I know are in a completely different environment from the script the thread.start is called from.

I can try it certainly.

**Comment by MrTeenageParker** [comment]
Suspicions confirmed:

`test-item.lua:8: attempt to call upvalue 'test' (a nil value)`

**Comment by ryanplusplus** [comment]
Interesting. The fact that threads are in a completely different environment seems to imply that what you're asking for may not work for anything that is passed by reference (ie: a table) instead of by value.

For your specific use case, are you able to pass multiple values and reconstruct the value on the receiving side? Or do you have a large or otherwise unwieldy table?

**Comment by MrTeenageParker** [comment]
The table is required because it has a bunch of functions and variables inside it, so either way, passing just a string or integer is impossible for my specific use case.

**Comment by MrTeenageParker** [comment]
They must be doing something weird with the threads, because it should have the same environment as the script in which the function was called in.

Functions passed to the thread should have the same environment regardless. I am not entirely sure as to why this is the case, but it could be an easy fix.

I assume all it would take is a setfenv, cause if I recall, thread.start() uses loadstring. So it should be as simple as setfenv the loadstring?

**Comment by ryanplusplus** [comment]
My guess is that it can't use the same environment because it creates an independent Lua state. It could copy this state, but then things that appear to be shared would not actually be shared (just copied).

**Comment by ryanplusplus** [comment]
Per https://github.com/luvit/luvit/issues/951#issuecomment-282597964 it is a separate Lua state so `setfenv` can't be used.

You might be able to work around this by extracting all of your functions to separate files so that they can be `load`ed or `require`d in from the thread function:

```lua
-- test.lua
local function test(arg1)
    print(arg1) -- print table
end

-- something_else.lua
thread.start(function()
   require 'test'({'item1', 'item2'})
end)
```

**Comment by MrTeenageParker** [comment]
but the thing is the table is in the environment in which the function would be called in with thread.start()

the table is passed similar to this:

```
local tbl = {} -- complex table

thread.start((function(args) end), tbl)
```

basically the table is required to be in the environment and can't be done another way (AFAIK).

**Comment by creationix** [comment]
Libuv event loops and lua states are both not thread safe.  Each OS thread has it's own independent libuv loop and lua state.  You can't pass live functions between states, everything needs to be serialized.

**Comment by MrTeenageParker** [comment]
Will there be a solution to my problem though? I imagine there must be something you could do to make it so you can, because there are plenty of cases where Lua has been used to make games and they allow separate threads to have the same environment as the script calling the thread?

I am sure there is something?

**Comment by creationix** [comment]
Keep in mind that lua calls coroutines "threads" which are more like green-threads.  They share lua state as well as libuv loop.

```lua
function run_in_thread()
  -- This code can suspend itself and allow other "threads" to run
end

coroutine.wrap(run_in_thread)()
```

**Comment by creationix** [comment]
As far as I know, it's not possible to share luajit states between real OS threads.  You can see here where the torch project has advanced serialization to make it feel like they are shared https://github.com/torch/threads

Also there are ways to serialize functions and unserialize them as RPC proxy functions on the other thread.  I do this heavily in my super-agent prototype project https://github.com/virgo-agent-toolkit/super-agent/blob/870f9480308f98099b395194a906ca8d2729ec05/agent/libs/rpc/init.lua

Do you need real OS threads or will lua coroutines do?  If you do need real threads and want to pass functions between them, I can help you design a way to serialize the functions across the lua state boundaries.

**Comment by MrTeenageParker** [comment]
I need a way to execute certain functions which will hang the entire program separate from the current thread. To elaborate more, I am making a project with Discordia which requires certain commands to be separated from the main thread otherwise the program will hang until those operations are complete.

**Comment by creationix** [comment]
If your functions are truly CPU blocking (not I/O blocking) then, yes, you need to run then in threads or other processes.  But I'm afraid you can't transfer lua functions between these OS threads, the VM simply doesn't support that.

**Comment by MrTeenageParker** [comment]
Even in tables? The functions will be transferred between tables?

I guess not. If there is ever a way, please make it so that the thread has the same environment as the script which called it, because this project that I am working on can't continue unless this is a feature.

I could write a c# program to execute the script in that way, but I am not entirely sure how to pass arguments to it.

Maybe this can be a new feature for the next version?

**Comment by creationix** [comment]
We did not design or implement lua, the language.  This is a constraint of the language and it's implementations.  The luvit project is a set of OS level bindings using non-blocking I/O so that you can script fast, efficient network servers.

The language does have coroutines which, combines with the non-blocking primitives in libuv, allows you do spawn lua threads (not OS threads) and do blocking I/O without blocking the main thread.

I seriously doubt we will ever add a feature to share lua references across OS threads since this requires massive changes to luajit itself.

But, I'm sure your problem can be solved with luvit, I just need to understand exactly what kind of blocking work you are doing.  

If it's anything involving I/O (file access, network I/O, timers, etc) then you can use coroutines and share lua references since everything will stay in a single OS thread.

If your task is CPU bound (such as heavy crypto, raytracing, bitcoin mining etc), then your worker will need to live in a new thread or process and communicate with the main app over some serialized channel.  You will pass input data to the worker, it will chew on that and return data at some point later through a callback into the main thread.

**Comment by MrTeenageParker** [comment]
Basically the Discordia bot (discord bot library) allows for Lua execution, and sometimes when executing Lua using loadstring it hangs the entire thread because of a loop or some other thing requiring a loop hangs the current thread, preventing any future processing.

I have tried using coroutines, but it has failed. I may be using them wrong, because I know only the basics of coroutine, nothing extensive.

**Comment by creationix** [comment]
It sounds like you need to write your code in a non-blocking way or use threads and pass data back and forth in serialized form.  It is correct that you should never create infinite loops in normal luvit code.

Maybe @SinisterRectus has tips for how to use discordia.

**Comment by SinisterRectus** [comment]
Ahoy. Discordia relies heavily on tables that have circular references, so you will not be able to easily serialize data and pass them to a separate thread. Like Tim said, unless you're doing something intensive using primitives, the best option is to use Lua coroutines. If you have a loop that blocks I/O, one option would be put a call to `timer.sleep` into the loop. This would yield the coroutine and allow the background HTTP and WebSocket connections to continue operating.

**Comment by MrTeenageParker** [comment]
The issue is that the Lua-execution bit allows for output to discord, so if there is a way to make it so that multiple people can use the Lua-execution function in which someone accidentally creates a infinite loop that blocks I/O that would be great.

**Comment by SinisterRectus** [comment]
That's an entirely different issue, one that should not exist if you follow my recommendation of restricting code execution only to yourself. If you want to discuss this further, open an issue on the Discordia repository, or visit our Discord channel.

**Comment by MrTeenageParker** [comment]
But the issue lies with the loadstring() function yielding, not specifically with Discordia. This happens with all things made with Luvit.

The problem is with the fact that thread.start doesn't allow functions to be passed and executed as second arguments. If this were possible that would allow for further possibilities.

So yes, this is an issue with Luvit and not Discordia.

**Comment by SinisterRectus** [comment]
Based on the conversation so far, it seems to me that your specific goal of passing Discordia objects to a new thread is impossible, and is not likely to ever be possible. Your general goal of preventing other users from breaking your application is outside of the scope of this discussion. This is a classic [XY problem](http://xyproblem.info/), so I invite you again to visit our Discord channel to maybe find the best solution.
