### ISSUE TITLE
Memory leak on keep-alive Connection

### ISSUE THREAD

**Issue by yaa110** [luvit/luvit#953]
I'm using luvit to serve a web app, it seems the `socket` remains open ([here](https://github.com/luvit/luvit/blob/master/deps/http.lua#L191)) and is not reused for keep-alive connections which causes memory leak.

**Comment by creationix** [comment]
Thanks for reporting.  If you're able, please submit a pull request with a proposed fix.  It would be great if we could also add a regression test somehow that prevents this from happening again in the future.

There is nobody actively maintaining this node-style stream code and I've been trying to move everyone to the newer coroutine style streams used by lit.

If you're unable or unwilling to submit a patch, leave this issue open and I'll see when I can get around to it.

Thanks for the report and sorry I don't have more resources to help.
