### ISSUE TITLE
Application code review before make PR

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvit#972]
please check https://github.com/luvit/luvit/compare/master...zhaozg:master  and give advice. I prepare do some change and make a final PR.

Cc @creationix @rphillips

thanks.

**Comment by creationix** [comment]
I looked briefly, don't have time right now for a through review.  I love the parts that fix bugs.

**Comment by zhaozg** [comment]
OK, I'll split bug fix parts out, and make PR.

**Comment by zhaozg** [comment]
bug fix parts merged at https://github.com/luvit/luvit/commit/0d2d2524cc0061a84d313ede2b275af037e1e827
