### ISSUE TITLE
http-codec imposes an 8K limit on form data

### ISSUE THREAD

**Issue by ryanplusplus** [luvit/luvit#976]
I'm trying to implement file upload using `"multipart/form-data` encoding, but `http-codec` throws an error if the file is > ~8k. Is there any way to work around this? If not, can this be made configurable somehow?

**Comment by creationix** [comment]
I thought the limit was only for the header section.  It shouldn't limit the body.  How are you hitting this error?

**Comment by ryanplusplus** [comment]
This is the form:

```html
  <form action="/upload" method="post" enctype="multipart/form-data">
    <label for="file">Filename</label>
    <input type="file" name="file" id="file" />
    <input type="submit" name="submit" value="Submit" />
  </form>
```

This is my middleware:

```lua
  app.use(weblit.logger)
  app.use(weblit.autoHeaders)
  app.use(weblit.static('static'))
```

And this is the route:

```lua
  app.route({ method = 'POST', path = '/upload' }, function(req, res)
    p(#req.body)
    res.code = 200
  end)
```

The interesting thing is that it fails _after_ my route handler runs.

After playing around more, it seems as though this is actually caused by `weblit.autoHeaders` middleware because `http-codec` doesn't raise an error if I remove it.

**Comment by ryanplusplus** [comment]
FYI the repo is here if you need to poke around: https://github.com/ryanplusplus/weblit-playground

**Comment by creationix** [comment]
Hmm, I can't reproduce the error.  It doesn't crash with the files I tested, some were megabytes in size.

I'm on linux with luvi v2.7.6

**Comment by creationix** [comment]
Well, I got it to reproduce now.  It reproduces in Firefox 53.0, but not in Chrome 58.0.

**Comment by creationix** [comment]
Strange indeed, it seems to send the browser the correct response and *then* crash while trying to parse the body *again* that it's already parsed (but this time it thinks it's a header and thus the size limit)

**Comment by creationix** [comment]
Thanks for the bug report!  It was indeed a bug from when I refactored http-codec.  It wasn't taking the index into account when measuring the size of the chunk.
https://github.com/luvit/lit/commit/33d569016c7d241735dddc155cec0f72026bdd00

Try again with updated http-codec version.

**Comment by ryanplusplus** [comment]
My bad, I should have let you know I was on Linux with Firefox 53 :)

Works great now. Thanks for taking the time to look into this!
