### ISSUE TITLE
Downloading Problem

### ISSUE THREAD

**Issue by JaredMFProgramming** [luvit/luvit#985]
Hey there, I cannot download Luvit on my computer, because everytime I try to, this happens:

```C:\Users\Owner>PowerShell -NoProfile -ExecutionPolicy unrestricted -Command "iex ((new-object net.webclient).DownloadString('https://github.com/luvit/lit/raw/master/get-lit.ps1'))"
Downloading https://github.com/luvit/luvi/releases/download/v2.7.6/luvi-regular-Windows-amd64.exe to luvi.exe
Downloading https://lit.luvit.io/packages/luvit/lit/v3.5.4.zip to lit.zip
Exception calling "DownloadFile" with "2" argument(s): "The remote server
returned an error: (502) Bad Gateway."
At line:25 char:3
+   $downloader.DownloadFile($url, $file)
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

C:/Users/tim/luvi/src/lua/luvibundle.lua:277: ERROR: C:\Users\Owner\lit.zip is not a zip file or a folder
Remove-Item : Cannot find path 'C:\Users\Owner\lit.zip' because it does not
exist.
At line:35 char:1
+ Remove-Item "lit.zip"
+ ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\Owner\lit.zip:String)
   [Remove-Item], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Remov
   eItemCommand

Start-Process : This command cannot be run due to the error: The system cannot
find the file specified.
At line:37 char:1
+ Start-Process "lit.exe" -ArgumentList "make lit://luvit/luvit luvit.e ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Start-Process], InvalidOp
   erationException
    + FullyQualifiedErrorId : InvalidOperationException,Microsoft.PowerShell.C
   ommands.StartProcessCommand


C:\Users\Owner>
```

Could you help me out?

**Comment by squeek502** [comment]
Looks like the lit server is down. @creationix ?

**Comment by iViscosity** [comment]
Any more information on this? Trying to install and I get the same error.

**Comment by zhaozg** [comment]
As alternative, I think you can download https://ci.appveyor.com/project/racker-buildbot/luvit/build/job/gbaopf15v3r7211l/artifacts or https://ci.appveyor.com/project/racker-buildbot/luvit/branch/master/job/7i7c0a8ct0mlass0/artifacts

1. goto https://ci.appveyor.com/project/racker-buildbot/luvit
2. click one job.
3. click ARTIFACTS
4. click file to download it

**Comment by creationix** [comment]
Yes, it was down again.  Sorry I don't have time to make this more robust at the moment.

**Comment by harule** [comment]
I am trying to install Luvit on my raspberry pi 3 (raspbian), however I still get the same error mentioned above (`lit.zip is not a zip file or a folder`).

Even if I try to double click on lit.zip in the file explorer, it keeps saying that the archive format was not recognized.

Any way to fix this? Thanks.

**Comment by rphillips** [comment]
restarted the server... should be good to go.

**Comment by rphillips** [comment]
setup a cron script to check the health and restart the server if need be.

**Comment by creationix** [comment]
I just had to restart the `luvit.io` process FWIW.

**Comment by rphillips** [comment]
just fixed the script to check both of them
