### ISSUE TITLE
Https certificate error

### ISSUE THREAD

**Issue by tigerism** [luvit/luvit#994]
I'm trying to send a GET request to `https://www.carbonitex.net/discord/api/listedbots` with coro-http, but I'm getting this error: `coro-http.lua:74: Error verifying peer: unable to get local issuer certificate`
People are able to GET the url with node.js just fine. 
I've also updated luvit to version 2.14.2.

**Comment by SinisterRectus** [comment]
2.14.2 fixes luvit's https module. To fix coro-http, you'll need to either manually install secure-socket from [luvit/lit](https://github.com/luvit/lit) or wait for a published version and install that from lit. The current version is 1.1.4. The new version should be either 1.1.5 or 1.2.0.

**Comment by Tigerism** [comment]
I manually updated secure-socket, and I'm having the same error.

**Comment by SinisterRectus** [comment]
Yeah, I just tested it. Apart from the fact that you also need to update coro-net and coro-http to get the TLS fix, this is a  different issue entirely.

This works for me in 2.14.2, though:

```lua
local https = require('https')
local parseUrl = require('http').parseUrl

local options = parseUrl("https://www.carbonitex.net/discord/api/listedbots")

https.get(options, function (res)
  p(res)
end)
```

**Comment by rphillips** [comment]
fetching `https://www.carbonitex.net/` seems to work

**Comment by SinisterRectus** [comment]
True, it also works with a fully updated coro-http. If you want to use coro-http, update manually. I'll see if I can work the new versions into the Discordia deps list. I can't remember why I did not update them already.

**Comment by SinisterRectus** [comment]
Discordia deps are now very removed from those that caused this issue, so we should be good here.
