### ISSUE TITLE
Certificate error during install

### ISSUE THREAD

**Issue by lettucemode** [luvit/luvit#997]
Hiya. I am trying to get luvit set up on my windows 10 machine. I ran the PowerShell command from here: https://luvit.io/install.html. When I did, lit built fine, but the luvi build threw this error: 

![image](https://user-images.githubusercontent.com/5483218/27669166-725b0a30-5c53-11e7-9b66-24ccdae0857f.png)

I've been trying to figure this out for a while to no avail. I tried building from the source as described later on in the instructions, but eventually ran into the same error. I know I need to do something with the certificates on my machine but I have no idea how to make this build process respect them. Would appreciate any help.

**Comment by creationix** [comment]
It's more likely a problem with my server.  I just manually updated the certs and restarted the server.  See if that helps.

**Comment by creationix** [comment]
![image](https://user-images.githubusercontent.com/89353/27798892-b09756e0-5fd8-11e7-996f-f85afcd92e95.png)

**Comment by Leka74** [comment]
It's happening again @creationix

**Comment by creationix** [comment]
Looks unrelated, file a new issue if you don't mind.

**Comment by lettucemode** [comment]
I ended up going with a different library for my solution. Might swing back to this someday.
