### ISSUE TITLE
Unable to install luvit because lit server is down

### ISSUE THREAD

**Issue by thedoctorate** [luvit/luvit#999]
The lit server (https://lit.luvit.io) seems to be down which is preventing me from installing luvit.

Error I receive:
`Exception calling "DownloadFile" with "2" argument(s): "The remote server
returned an error: (502) Bad Gateway."`

@creationix

**Comment by rphillips** [comment]
I restart the service. It's running again.

**Comment by creationix** [comment]
Thanks!
